# Generated by Django 5.2.8 on 2026-01-23 18:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("company", "0003_company_agent_full_name_company_agent_post_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("rules", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("EXEC", "Exec"),
                            ("ADMIN", "Admin"),
                            ("COMPLIANCE", "Compliance"),
                            ("BILLING", "Billing"),
                            ("IMPLEMENTATION", "Implementation"),
                            ("OPERATION", "Operation"),
                            ("DIRECTOR", "Director"),
                            ("MANAGER", "Manager"),
                            ("SPECIALIST", "Specialist"),
                            ("FINANCE", "Finance"),
                            ("EMPLOYEE", "Employee"),
                        ],
                        default="EMPLOYEE",
                        max_length=50,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="PermissionBulkUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("changes", models.JSONField(default=dict)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="PermissionMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("EXEC", "Exec"),
                            ("ADMIN", "Admin"),
                            ("COMPLIANCE", "Compliance"),
                            ("BILLING", "Billing"),
                            ("IMPLEMENTATION", "Implementation"),
                            ("OPERATION", "Operation"),
                            ("DIRECTOR", "Director"),
                            ("MANAGER", "Manager"),
                            ("SPECIALIST", "Specialist"),
                            ("FINANCE", "Finance"),
                            ("EMPLOYEE", "Employee"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("ALL", "All"),
                            ("RULE", "Regulation"),
                            ("COMPANY", "Company"),
                            ("PAYROLL", "Payroll"),
                            ("PERIOD", "Payroll Period"),
                            ("EMPLOYEE", "Employee"),
                            ("REPORT", "Reports"),
                            ("USER", "User Management"),
                            ("ROLE", "Role Management"),
                            ("COMPANY_USER", "Company User Management"),
                            ("NOTIFICATION", "Notification Management"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ALL", "All"),
                            ("CREATE", "Create"),
                            ("READ", "Read"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("EXECUTE", "Execute"),
                            ("TRANSFER", "Transfer"),
                            ("APPROVE", "Approve"),
                            ("ASSIGN", "Assign"),
                            ("EXPORT", "Export"),
                            ("IMPORT", "Import"),
                        ],
                        max_length=50,
                    ),
                ),
                ("allowed", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Permission Matrices",
                "ordering": ["role", "domain", "action"],
                "indexes": [
                    models.Index(
                        fields=["role", "domain", "action"],
                        name="accounts_pe_role_c77686_idx",
                    ),
                    models.Index(fields=["role"], name="accounts_pe_role_5b0f7a_idx"),
                ],
                "unique_together": {("role", "domain", "action")},
            },
        ),
        migrations.CreateModel(
            name="RoleHierarchy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent", models.CharField(max_length=50)),
                ("child", models.CharField(max_length=50)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["parent"], name="accounts_ro_parent_32c348_idx"
                    ),
                    models.Index(fields=["child"], name="accounts_ro_child_951452_idx"),
                ],
                "unique_together": {("parent", "child")},
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("surname", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("notify_by_email", models.BooleanField(default=True)),
                ("notify_by_sms", models.BooleanField(default=False)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "notification_frequency",
                    models.CharField(
                        choices=[
                            ("IMMEDIATE", "Immediately"),
                            ("DAILY", "Daily Digest"),
                            ("WEEKLY", "Weekly Digest"),
                        ],
                        default="IMMEDIATE",
                        max_length=20,
                    ),
                ),
                ("two_factor_enabled", models.BooleanField(default=False)),
                (
                    "last_password_change",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "User Login"),
                            ("LOGOUT", "User Logout"),
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("VIEW", "View"),
                            ("EXPORT", "Export"),
                            ("PERMISSION_CHANGE", "Permission Change"),
                            ("SECURITY_EVENT", "Security Event"),
                            ("OTHER", "Other"),
                            ("NOTIFICATION_CREATED", "Notification Created"),
                            ("NOTIFICATION_READ", "Notification Read"),
                            ("COMPANY_ACCESS_GRANTED", "Company Access Granted"),
                            ("COMPANY_ACCESS_REVOKED", "Company Access Revoked"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target", models.CharField(blank=True, max_length=255, null=True)),
                ("details", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="company.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="accounts_au_user_id_7b1069_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="accounts_au_action_c683b9_idx",
                    ),
                    models.Index(
                        fields=["company", "created_at"],
                        name="accounts_au_company_db2e10_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="accounts_au_created_606b86_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("GLOBAL", "Global - All Companies"),
                            ("COMPANY", "Company-specific"),
                            ("DEPARTMENT", "Department-specific"),
                            ("REGION", "Region-specific"),
                        ],
                        default="GLOBAL",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "permissions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores role permissions in format: {'DOMAIN': ['ACTION1', 'ACTION2']}",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["scope", "is_active"],
                        name="accounts_cu_scope_07f60c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "System Notification"),
                            ("PAYROLL", "Payroll Update"),
                            ("APPROVAL", "Approval Required"),
                            ("DEADLINE", "Deadline Reminder"),
                            ("EMPLOYEE", "Employee Action"),
                            ("COMPLIANCE", "Compliance Alert"),
                            ("SECURITY", "Security Alert"),
                            ("BILLING", "Billing Update"),
                            ("SUPPORT", "Support Response"),
                        ],
                        default="SYSTEM",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                            ("INFO", "Informational"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                ("action_url", models.URLField(blank=True, null=True)),
                ("action_label", models.CharField(blank=True, max_length=100)),
                ("reference_model", models.CharField(blank=True, max_length=50)),
                ("reference_id", models.IntegerField(blank=True, null=True)),
                ("read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("archived", models.BooleanField(default=False)),
                ("email_sent", models.BooleanField(default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("sms_sent", models.BooleanField(default=False)),
                ("sms_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="company.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "accounts_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "read", "archived"],
                        name="accounts_no_user_id_41f18a_idx",
                    ),
                    models.Index(
                        fields=["user", "notification_type"],
                        name="accounts_no_user_id_65e69b_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="accounts_no_user_id_501ff2_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="accounts_no_expires_c7af83_idx"
                    ),
                    models.Index(
                        fields=["company"], name="accounts_no_company_5cb247_idx"
                    ),
                    models.Index(
                        fields=["priority", "created_at"],
                        name="accounts_no_priorit_81b80c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("ADMIN", "Company Administrator"),
                            ("PAYROLL_MANAGER", "Payroll Manager"),
                            ("HR_MANAGER", "HR Manager"),
                            ("FINANCE", "Finance Team"),
                            ("MANAGER", "Department Manager"),
                            ("VIEWER", "Viewer"),
                            ("EMPLOYEE", "Employee (Self-Service)"),
                        ],
                        default="VIEWER",
                        max_length=50,
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional permissions specific to this user-company relationship",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("access_granted_at", models.DateTimeField(auto_now_add=True)),
                ("access_revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_access_at", models.DateTimeField(blank=True, null=True)),
                (
                    "access_granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorized_users",
                        to="company.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Company Access",
                "verbose_name_plural": "User Company Access",
                "db_table": "accounts_user_company",
                "indexes": [
                    models.Index(
                        fields=["user", "company"],
                        name="accounts_us_user_id_3e49cf_idx",
                    ),
                    models.Index(
                        fields=["company", "role"],
                        name="accounts_us_company_13b364_idx",
                    ),
                    models.Index(
                        fields=["user", "is_active"],
                        name="accounts_us_user_id_a5364b_idx",
                    ),
                    models.Index(fields=["role"], name="accounts_us_role_a7510e_idx"),
                ],
                "unique_together": {("user", "company")},
            },
        ),
        migrations.CreateModel(
            name="UserContextMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "context_key",
                    models.CharField(
                        help_text="The key of the context variable (e.g., 'selected_company_id')",
                        max_length=100,
                    ),
                ),
                (
                    "context_value",
                    models.CharField(
                        help_text="The value of the context variable", max_length=255
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Context Mapping",
                "verbose_name_plural": "User Context Mappings",
                "unique_together": {("user", "context_key")},
            },
        ),
    ]
