# Generated by Django 5.2.8 on 2026-01-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='force_password_change',
            field=models.BooleanField(default=False, help_text='If True, user is redirected to password change on login.'),
        ),
    ]
