# Generated by Django 5.2.8 on 2026-01-24 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_force_password_change'),
        ('company', '0004_clientgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='usercompany',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usercontextmapping',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='accounts_au_user_id_7b1069_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='accounts_au_action_c683b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='accounts_au_company_db2e10_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='accounts_au_created_606b86_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='accounts_no_user_id_41f18a_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='accounts_no_user_id_65e69b_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='accounts_no_user_id_501ff2_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='accounts_no_expires_c7af83_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='accounts_no_company_5cb247_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='accounts_no_priorit_81b80c_idx',
        ),
        migrations.RemoveIndex(
            model_name='usercompany',
            name='accounts_us_user_id_a5364b_idx',
        ),
        migrations.RemoveIndex(
            model_name='usercompany',
            name='accounts_us_role_a7510e_idx',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='email_sent',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='email_sent_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sms_sent',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sms_sent_at',
        ),
        migrations.AddField(
            model_name='user',
            name='client_group',
            field=models.ForeignKey(blank=True, help_text='Assigning a group gives this user access to ALL companies in that group.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='company.clientgroup'),
        ),
        migrations.AlterField(
            model_name='customrole',
            name='permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EXEC', 'Exec'), ('ADMIN', 'Admin'), ('COMPLIANCE', 'Compliance'), ('BILLING', 'Billing'), ('IMPLEMENTATION', 'Implementation'), ('OPERATION', 'Operation'), ('DIRECTOR', 'Director'), ('MANAGER', 'Manager'), ('SPECIALIST', 'Specialist'), ('FINANCE', 'Finance'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', help_text='The primary role determining user permissions.', max_length=50),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='usercontextmapping',
            name='context_key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usercontextmapping',
            name='context_value',
            field=models.CharField(max_length=255),
        ),
    ]
