# Generated by Django 5.2.8 on 2026-01-24 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_auditlog_options_alter_notification_options_and_more'),
        ('company', '0004_clientgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.AlterModelOptions(
            name='customrole',
            options={},
        ),
        migrations.AlterModelOptions(
            name='permissionbulkupdate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='permissionmatrix',
            options={'ordering': ['role', 'domain', 'action']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveIndex(
            model_name='customrole',
            name='accounts_cu_scope_07f60c_idx',
        ),
        migrations.RemoveIndex(
            model_name='permissionmatrix',
            name='accounts_pe_role_5b0f7a_idx',
        ),
        migrations.RemoveIndex(
            model_name='rolehierarchy',
            name='accounts_ro_parent_32c348_idx',
        ),
        migrations.RemoveIndex(
            model_name='rolehierarchy',
            name='accounts_ro_child_951452_idx',
        ),
        migrations.RemoveIndex(
            model_name='usercompany',
            name='accounts_us_user_id_3e49cf_idx',
        ),
        migrations.RemoveIndex(
            model_name='usercompany',
            name='accounts_us_company_13b364_idx',
        ),
        migrations.RemoveField(
            model_name='customrole',
            name='description',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='action_label',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='action_url',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='company',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='read_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='reference_model',
        ),
        migrations.RemoveField(
            model_name='permissionbulkupdate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='usercompany',
            name='access_revoked_at',
        ),
        migrations.RemoveField(
            model_name='usercompany',
            name='last_access_at',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customrole',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customrole',
            name='scope',
            field=models.CharField(default='GLOBAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EXEC', 'Exec'), ('ADMIN', 'Admin'), ('COMPLIANCE', 'Compliance'), ('BILLING', 'Billing'), ('IMPLEMENTATION', 'Implementation'), ('OPERATION', 'Operation'), ('DIRECTOR', 'Director'), ('MANAGER', 'Manager'), ('SPECIALIST', 'Specialist'), ('FINANCE', 'Finance'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=50),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='access_granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Company Administrator'), ('PAYROLL_MANAGER', 'Payroll Manager'), ('HR_MANAGER', 'HR Manager'), ('FINANCE', 'Finance Team'), ('MANAGER', 'Department Manager'), ('VIEWER', 'Viewer'), ('EMPLOYEE', 'Employee')], default='VIEWER', max_length=50),
        ),
        migrations.AlterField(
            model_name='usercontextmapping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='force_password_change',
            field=models.BooleanField(default=False, help_text='User redirected to change password on login.'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='accounts_au_user_id_7b1069_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='accounts_au_action_c683b9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['company', 'created_at'], name='accounts_au_company_db2e10_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='accounts_au_created_606b86_idx'),
        ),
        migrations.AlterModelTable(
            name='notification',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usercompany',
            table=None,
        ),
    ]
