# Generated by Django 5.2.8 on 2026-02-02 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_auditlog_options_alter_customrole_options_and_more'),
        ('company', '0004_clientgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DIRECTOR', 'Director'), ('MANAGER', 'Manager'), ('SPECIALIST', 'Specialist'), ('FINANCE', 'Finance'), ('VIEWER', 'Read Only')], default='VIEWER', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_contexts', to='company.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Assignment',
                'verbose_name_plural': 'User Assignments',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
