# Generated by Django 5.2.8 on 2026-02-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_usercontext"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontext",
            name="preferred_language",
            field=models.CharField(
                choices=[("en", "English"), ("es", "Español"), ("pt", "Português")],
                default="en-gb",
                max_length=10,
                verbose_name="Preferred language",
            ),
        ),
    ]
