# Generated by Django 5.2.8 on 2026-02-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_usercontext_preferred_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercontext",
            name="preferred_language",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_language",
            field=models.CharField(
                choices=[("en", "English"), ("es", "Español"), ("pt", "Português")],
                default="en-gb",
                max_length=30,
            ),
        ),
    ]
