# Generated by Django 5.2.8 on 2025-11-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso2_code', models.CharField(max_length=2, unique=True, verbose_name='ISO 2-Letter Code')),
                ('iso3_code', models.CharField(max_length=3, unique=True, verbose_name='ISO 3-Letter Code')),
                ('name', models.CharField(max_length=100, verbose_name='Country Name')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('IMPLEMENTING', 'Implementing'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=15, verbose_name='Country Status')),
                ('official_language', models.CharField(max_length=100, verbose_name='Official Language')),
                ('currency_name', models.CharField(max_length=50, verbose_name='Currency')),
                ('currency_code', models.CharField(max_length=3, verbose_name='Currency Code')),
                ('fiscal_year_start', models.CharField(max_length=20, verbose_name='Fiscal Year Starts')),
                ('fiscal_year_end', models.CharField(max_length=20, verbose_name='Fiscal Year Ends')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('numbering_format', models.CharField(choices=[('1,000.00', '1,000.00 (dot as decimal separator)'), ('1.000,00', '1.000,00 (comma as decimal separator)')], default='1,000.00', max_length=10, verbose_name='Numbering Format')),
                ('currency_position', models.CharField(choices=[('BEFORE', 'Currency Code before amount (e.g. EUR 1,000)'), ('AFTER', 'Currency Code after amount (e.g. 1,000 EUR)')], default='BEFORE', max_length=10, verbose_name='Currency Code Position')),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY/MM/DD', 'YYYY/MM/DD'), ('YYYY/DD/MM', 'YYYY/DD/MM')], default='DD/MM/YYYY', max_length=12, verbose_name='Date Format')),
                ('decimals', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=2, verbose_name='Decimal Places')),
                ('archive', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=1, verbose_name='Archive Format')),
            ],
        ),
    ]
