# Generated by Django 5.2.8 on 2026-01-14 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_code', models.CharField(blank=True, max_length=50, null=True)),
                ('element_description', models.CharField(max_length=150)),
                ('element_name', models.CharField(max_length=150)),
                ('element_status', models.CharField(blank=True, choices=[('Visible', 'Visible'), ('Hidden', 'Hidden')], max_length=15, null=True)),
                ('element_account', models.IntegerField(blank=True, null=True)),
                ('element_map_code', models.IntegerField(blank=True, null=True)),
                ('element_gl_account', models.IntegerField(blank=True, null=True)),
                ('element_frequency', models.CharField(blank=True, choices=[('Recurring', 'Recurring'), ('Non-recurring', 'Non-recurring')], max_length=15, null=True)),
                ('element_type', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Irregular', 'Irregular')], max_length=50, null=True)),
                ('element_class', models.CharField(blank=True, choices=[('Standard', 'Standard'), ('Statutory', 'Statutory')], max_length=50, null=True)),
                ('element_category', models.CharField(blank=True, choices=[('Payment', 'Payment'), ('Deduction', 'Deduction'), ('Notional', 'Notional'), ('Base', 'Base'), ('Gross up', 'Gross up'), ('ER Contribution', 'ER Contribution'), ('ER Cost', 'ER Cost')], max_length=50, null=True)),
                ('element_taxable', models.BooleanField(default=False)),
                ('element_tax_flat', models.BooleanField(default=False)),
                ('element_tax_irregular', models.BooleanField(default=False)),
                ('element_social_securitable', models.BooleanField(default=False)),
                ('element_pensionable', models.BooleanField(default=False)),
                ('element_payable', models.BooleanField(default=False)),
                ('element_calculate', models.BooleanField(default=False)),
                ('is_auto_generated', models.BooleanField(default=False, editable=False, help_text='Flag to identify system-generated shadow elements (YTD, Bases, etc.)')),
                ('element_categorytype', models.CharField(blank=True, choices=[('Bracketable', 'Bracketable'), ('Prorational', 'Prorational'), ('Pension', 'Pension'), ('Formulae', 'Formulae'), ('Base', 'Base')], max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('archive', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=1)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='country.country')),
            ],
            options={
                'ordering': ['element_code'],
                'unique_together': {('country', 'element_code')},
            },
        ),
    ]
