# Generated by Django 5.2.8 on 2026-01-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='element_account',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='element',
            name='element_gl_account',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='element',
            name='element_map_code',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
