# Generated by Django 5.2.8 on 2025-11-18 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
        ('elements', '0003_alter_element_country_and_more'),
        ('regulations', '0002_regulations_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_jurisdiction', models.CharField(blank=True, max_length=150, null=True)),
                ('table_type', models.CharField(blank=True, choices=[('Single', 'Single'), ('Parent', 'Parent'), ('Married', 'Married')], max_length=15, null=True)),
                ('ss_category', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], max_length=15, null=True)),
                ('base_frequency', models.CharField(blank=True, choices=[('Annually', 'Annually'), ('Monthly', 'Monthly'), ('Semi-Monthly', 'Semi-Monthly'), ('Fortnightly', 'Fortnightly'), ('Weekly', 'Weekly')], max_length=15, null=True)),
                ('bracket_00', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True)),
                ('bracket_01', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True)),
                ('bracket_02', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True)),
                ('bracket_03', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True)),
                ('bracket_04', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True)),
                ('bracket_05', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True)),
                ('bracket_06', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True)),
                ('bracket_07', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True)),
                ('bracket_08', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True)),
                ('bracket_09', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True)),
                ('bracket_10', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True)),
                ('bracket_11', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True)),
                ('bracket_12', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True)),
                ('bracket_13', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True)),
                ('bracket_14', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True)),
                ('bracket_15', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True)),
                ('rate_00', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True)),
                ('rate_01', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True)),
                ('rate_02', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True)),
                ('rate_03', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True)),
                ('rate_04', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True)),
                ('rate_05', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True)),
                ('rate_06', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True)),
                ('rate_07', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True)),
                ('rate_08', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True)),
                ('rate_09', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True)),
                ('rate_10', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True)),
                ('rate_11', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True)),
                ('rate_12', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True)),
                ('rate_13', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True)),
                ('rate_14', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True)),
                ('rate_15', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.country')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_bases', to='elements.element')),
                ('element_base', models.ForeignKey(blank=True, limit_choices_to={'element_categorytype': 'Base'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_calculation_bases', to='elements.element')),
                ('regulations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_bases', to='regulations.regulations')),
            ],
        ),
    ]
