from __future__ import annotations

from datetime import date
from types import SimpleNamespace

from django.conf import settings
from django.templatetags.static import static
from django.utils.translation import gettext as _


LAST_REVIEWED_ON = date(2026, 4, 18)

DEFAULT_EMPLOYER_CONSIDERATIONS = [
    "Confirm the employer registration path before the first live payroll.",
    "Validate withholding, contribution, and remittance ownership against the relevant authority.",
    "Keep country-level payroll calendars and statutory references under version control.",
]


def _safe_static(path: str) -> str:
    try:
        return static(path)
    except ValueError:
        return f"{settings.STATIC_URL.rstrip('/')}/{path.lstrip('/')}"


RAW_COUNTRIES = [
    {
        "country_name": "Angola",
        "official_name": "Republic of Angola",
        "slug": "angola",
        "iso_code": "AO",
        "region": "Africa",
        "capital": "Luanda",
        "currency": "Angolan kwanza (AOA)",
        "pay_currency": "AOA",
        "internet_domain": ".ao",
        "tax_authority_name": "General Tax Administration (AGT)",
        "social_security_authority_name": "National Institute of Social Security (INSS)",
    },
    {
        "country_name": "Argentina",
        "official_name": "Argentine Republic",
        "slug": "argentina",
        "iso_code": "AR",
        "region": "South America",
        "capital": "Buenos Aires",
        "currency": "Argentine peso (ARS)",
        "pay_currency": "ARS",
        "internet_domain": ".ar",
        "tax_authority_name": "Agency for Collection and Customs Control (ARCA)",
        "social_security_authority_name": "National Social Security Administration (ANSES)",
    },
    {
        "country_name": "Australia",
        "official_name": "Commonwealth of Australia",
        "slug": "australia",
        "iso_code": "AU",
        "region": "Asia-Pacific",
        "capital": "Canberra",
        "currency": "Australian dollar (AUD)",
        "pay_currency": "AUD",
        "internet_domain": ".au",
        "tax_authority_name": "Australian Taxation Office (ATO)",
        "tax_year": "1 July to 30 June",
    },
    {
        "country_name": "Austria",
        "official_name": "Republic of Austria",
        "slug": "austria",
        "iso_code": "AT",
        "region": "Europe",
        "capital": "Vienna",
        "currency": "Euro (EUR)",
        "pay_currency": "EUR",
        "internet_domain": ".at",
        "tax_authority_name": "Tax Authority Austria (Finanzamt Österreich)",
        "social_security_authority_name": "Federation of Austrian Social Insurance Institutions",
    },
    {
        "country_name": "Belgium",
        "official_name": "Kingdom of Belgium",
        "slug": "belgium",
        "iso_code": "BE",
        "region": "Europe",
        "capital": "Brussels",
        "currency": "Euro (EUR)",
        "pay_currency": "EUR",
        "internet_domain": ".be",
        "tax_authority_name": "Federal Public Service Finance",
        "social_security_authority_name": "National Social Security Office (NSSO)",
    },
    {
        "country_name": "Bolivia",
        "official_name": "Plurinational State of Bolivia",
        "slug": "bolivia",
        "iso_code": "BO",
        "region": "South America",
        "capital": "Sucre (constitutional); La Paz (seat of government)",
        "currency": "Boliviano (BOB)",
        "pay_currency": "BOB",
        "internet_domain": ".bo",
        "tax_authority_name": "National Tax Service (SIN)",
    },
    {
        "country_name": "Botswana",
        "official_name": "Republic of Botswana",
        "slug": "botswana",
        "iso_code": "BW",
        "region": "Africa",
        "capital": "Gaborone",
        "currency": "Botswana pula (BWP)",
        "pay_currency": "BWP",
        "internet_domain": ".bw",
        "tax_authority_name": "Botswana Unified Revenue Service (BURS)",
    },
    {
        "country_name": "Brazil",
        "official_name": "Federative Republic of Brazil",
        "slug": "brazil",
        "iso_code": "BR",
        "region": "South America",
        "capital": "Brasilia",
        "currency": "Brazilian real (BRL)",
        "pay_currency": "BRL",
        "internet_domain": ".br",
        "tax_authority_name": "Secretariat of the Federal Revenue of Brazil (Receita Federal)",
        "social_security_authority_name": "National Institute of Social Security (INSS)",
    },
    {
        "country_name": "Canada",
        "official_name": "Canada",
        "slug": "canada",
        "iso_code": "CA",
        "region": "North America",
        "capital": "Ottawa",
        "currency": "Canadian dollar (CAD)",
        "pay_currency": "CAD",
        "internet_domain": ".ca",
        "tax_authority_name": "Canada Revenue Agency (CRA)",
        "social_security_authority_name": "Service Canada",
        "authority_note": "Canada Payroll Deductions rules are administered across tax, pension, and employment-insurance programmes.",
    },
    {
        "country_name": "Chile",
        "official_name": "Republic of Chile",
        "slug": "chile",
        "iso_code": "CL",
        "region": "South America",
        "capital": "Santiago",
        "currency": "Chilean peso (CLP)",
        "pay_currency": "CLP",
        "internet_domain": ".cl",
        "tax_authority_name": "Internal Revenue Service (Servicio de Impuestos Internos, SII)",
        "social_security_authority_name": "Social Security Institute (Instituto de Previsión Social, IPS)",
    },
    {
        "country_name": "Colombia",
        "official_name": "Republic of Colombia",
        "slug": "colombia",
        "iso_code": "CO",
        "region": "South America",
        "capital": "Bogota",
        "currency": "Colombian peso (COP)",
        "pay_currency": "COP",
        "internet_domain": ".co",
        "tax_authority_name": "National Tax and Customs Directorate (DIAN)",
        "social_security_authority_name": "Pensions and Parafiscal Management Unit (UGPP)",
    },
    {
        "country_name": "Costa Rica",
        "official_name": "Republic of Costa Rica",
        "slug": "costa-rica",
        "iso_code": "CR",
        "region": "North America",
        "capital": "San Jose",
        "currency": "Costa Rican colon (CRC)",
        "pay_currency": "CRC",
        "internet_domain": ".cr",
        "tax_authority_name": "General Directorate of Taxation",
        "social_security_authority_name": "Costa Rican Social Security Fund (CCSS)",
    },
    {
        "country_name": "Denmark",
        "official_name": "Kingdom of Denmark",
        "slug": "denmark",
        "iso_code": "DK",
        "region": "Europe",
        "capital": "Copenhagen",
        "currency": "Danish krone (DKK)",
        "pay_currency": "DKK",
        "internet_domain": ".dk",
        "tax_authority_name": "Danish Tax Agency (Skattestyrelsen)",
    },
    {
        "country_name": "Ecuador",
        "official_name": "Republic of Ecuador",
        "slug": "ecuador",
        "iso_code": "EC",
        "region": "South America",
        "capital": "Quito",
        "currency": "United States dollar (USD)",
        "pay_currency": "USD",
        "internet_domain": ".ec",
        "tax_authority_name": "Internal Revenue Service (SRI)",
        "social_security_authority_name": "Ecuadorian Social Security Institute (IESS)",
    },
    {
        "country_name": "Egypt",
        "official_name": "Arab Republic of Egypt",
        "slug": "egypt",
        "iso_code": "EG",
        "region": "Africa",
        "capital": "Cairo",
        "currency": "Egyptian pound (EGP)",
        "pay_currency": "EGP",
        "internet_domain": ".eg",
        "tax_authority_name": "Egyptian Tax Authority",
        "social_security_authority_name": "National Organization for Social Insurance (NOSI)",
    },
    {
        "country_name": "Estonia",
        "official_name": "Republic of Estonia",
        "slug": "estonia",
        "iso_code": "EE",
        "region": "Europe",
        "capital": "Tallinn",
        "currency": "Euro (EUR)",
        "pay_currency": "EUR",
        "internet_domain": ".ee",
        "tax_authority_name": "Estonian Tax and Customs Board",
        "social_security_authority_name": "Social Insurance Board",
    },
    {
        "country_name": "Finland",
        "official_name": "Republic of Finland",
        "slug": "finland",
        "iso_code": "FI",
        "region": "Europe",
        "capital": "Helsinki",
        "currency": "Euro (EUR)",
        "pay_currency": "EUR",
        "internet_domain": ".fi",
        "tax_authority_name": "Finnish Tax Administration (Vero)",
    },
    {
        "country_name": "Guatemala",
        "official_name": "Republic of Guatemala",
        "slug": "guatemala",
        "iso_code": "GT",
        "region": "North America",
        "capital": "Guatemala City",
        "currency": "Guatemalan quetzal (GTQ)",
        "pay_currency": "GTQ",
        "internet_domain": ".gt",
        "tax_authority_name": "Superintendence of Tax Administration (SAT)",
        "social_security_authority_name": "Guatemalan Social Security Institute (IGSS)",
    },
    {
        "country_name": "Hungary",
        "official_name": "Hungary",
        "slug": "hungary",
        "iso_code": "HU",
        "region": "Europe",
        "capital": "Budapest",
        "currency": "Hungarian forint (HUF)",
        "pay_currency": "HUF",
        "internet_domain": ".hu",
        "tax_authority_name": "National Tax and Customs Administration (NAV)",
    },
    {
        "country_name": "India",
        "official_name": "Republic of India",
        "slug": "india",
        "iso_code": "IN",
        "region": "Asia-Pacific",
        "capital": "New Delhi",
        "currency": "Indian rupee (INR)",
        "pay_currency": "INR",
        "internet_domain": ".in",
        "tax_authority_name": "Income Tax Department",
        "social_security_authority_name": "Employees' Provident Fund Organisation (EPFO); Employees' State Insurance Corporation (ESIC)",
        "tax_year": "1 April to 31 March",
        "authority_note": "India payroll social-security obligations are split across provident-fund and state-insurance bodies.",
    },
    {
        "country_name": "Indonesia",
        "official_name": "Republic of Indonesia",
        "slug": "indonesia",
        "iso_code": "ID",
        "region": "Asia-Pacific",
        "capital": "Jakarta",
        "currency": "Indonesian rupiah (IDR)",
        "pay_currency": "IDR",
        "internet_domain": ".id",
        "tax_authority_name": "Directorate General of Taxes (DJP)",
        "social_security_authority_name": "BPJS Ketenagakerjaan; BPJS Kesehatan",
        "authority_note": "Indonesia operates separate employment and health social-security institutions.",
    },
    {
        "country_name": "Ireland",
        "official_name": "Ireland",
        "slug": "ireland",
        "iso_code": "IE",
        "region": "Europe",
        "capital": "Dublin",
        "currency": "Euro (EUR)",
        "pay_currency": "EUR",
        "internet_domain": ".ie",
        "tax_authority_name": "Revenue Commissioners",
        "social_security_authority_name": "Department of Social Protection",
        "tax_year": "Calendar year",
        "authority_note": "Irish employers operate PAYE with PRSI remitted through Revenue and administered within the Department of Social Protection framework.",
    },
    {
        "country_name": "Kazakhstan",
        "official_name": "Republic of Kazakhstan",
        "slug": "kazakhstan",
        "iso_code": "KZ",
        "region": "Asia-Pacific",
        "capital": "Astana",
        "currency": "Kazakhstani tenge (KZT)",
        "pay_currency": "KZT",
        "internet_domain": ".kz",
        "tax_authority_name": "State Revenue Committee",
        "social_security_authority_name": "State Social Insurance Fund",
    },
    {
        "country_name": "Kenya",
        "official_name": "Republic of Kenya",
        "slug": "kenya",
        "iso_code": "KE",
        "region": "Africa",
        "capital": "Nairobi",
        "currency": "Kenyan shilling (KES)",
        "pay_currency": "KES",
        "internet_domain": ".ke",
        "tax_authority_name": "Kenya Revenue Authority (KRA)",
        "social_security_authority_name": "National Social Security Fund (NSSF)",
    },
    {
        "country_name": "Latvia",
        "official_name": "Republic of Latvia",
        "slug": "latvia",
        "iso_code": "LV",
        "region": "Europe",
        "capital": "Riga",
        "currency": "Euro (EUR)",
        "pay_currency": "EUR",
        "internet_domain": ".lv",
        "tax_authority_name": "State Revenue Service (VID)",
        "social_security_authority_name": "State Social Insurance Agency (VSAA)",
    },
    {
        "country_name": "Lithuania",
        "official_name": "Republic of Lithuania",
        "slug": "lithuania",
        "iso_code": "LT",
        "region": "Europe",
        "capital": "Vilnius",
        "currency": "Euro (EUR)",
        "pay_currency": "EUR",
        "internet_domain": ".lt",
        "tax_authority_name": "State Tax Inspectorate (VMI)",
        "social_security_authority_name": "State Social Insurance Fund Board (Sodra)",
    },
    {
        "country_name": "Malaysia",
        "official_name": "Malaysia",
        "slug": "malaysia",
        "iso_code": "MY",
        "region": "Asia-Pacific",
        "capital": "Kuala Lumpur",
        "currency": "Malaysian ringgit (MYR)",
        "pay_currency": "MYR",
        "internet_domain": ".my",
        "tax_authority_name": "Inland Revenue Board of Malaysia (LHDN)",
        "social_security_authority_name": "Employees Provident Fund (EPF); Social Security Organisation (SOCSO)",
        "authority_note": "Malaysia payroll contributions are administered through separate retirement-savings and social-insurance bodies.",
    },
    {
        "country_name": "Malta",
        "official_name": "Republic of Malta",
        "slug": "malta",
        "iso_code": "MT",
        "region": "Europe",
        "capital": "Valletta",
        "currency": "Euro (EUR)",
        "pay_currency": "EUR",
        "internet_domain": ".mt",
        "tax_authority_name": "Commissioner for Revenue",
        "social_security_authority_name": "Social Security Department",
    },
    {
        "country_name": "Mexico",
        "official_name": "United Mexican States",
        "slug": "mexico",
        "iso_code": "MX",
        "region": "North America",
        "capital": "Mexico City",
        "currency": "Mexican peso (MXN)",
        "pay_currency": "MXN",
        "internet_domain": ".mx",
        "tax_authority_name": "Tax Administration Service (SAT)",
        "social_security_authority_name": "Mexican Social Security Institute (IMSS)",
    },
    {
        "country_name": "Netherlands",
        "official_name": "Kingdom of the Netherlands",
        "slug": "netherlands",
        "iso_code": "NL",
        "region": "Europe",
        "capital": "Amsterdam",
        "currency": "Euro (EUR)",
        "pay_currency": "EUR",
        "internet_domain": ".nl",
        "tax_authority_name": "Belastingdienst",
        "social_security_authority_name": "Social Insurance Bank (SVB)",
    },
    {
        "country_name": "New Zealand",
        "official_name": "New Zealand",
        "slug": "new-zealand",
        "iso_code": "NZ",
        "region": "Asia-Pacific",
        "capital": "Wellington",
        "currency": "New Zealand dollar (NZD)",
        "pay_currency": "NZD",
        "internet_domain": ".nz",
        "tax_authority_name": "Inland Revenue",
        "tax_year": "1 April to 31 March",
    },
    {
        "country_name": "Nigeria",
        "official_name": "Federal Republic of Nigeria",
        "slug": "nigeria",
        "iso_code": "NG",
        "region": "Africa",
        "capital": "Abuja",
        "currency": "Nigerian naira (NGN)",
        "pay_currency": "NGN",
        "internet_domain": ".ng",
        "tax_authority_name": "Federal Inland Revenue Service (FIRS)",
        "social_security_authority_name": "National Social Insurance Trust Fund (NSITF)",
    },
    {
        "country_name": "Norway",
        "official_name": "Kingdom of Norway",
        "slug": "norway",
        "iso_code": "NO",
        "region": "Europe",
        "capital": "Oslo",
        "currency": "Norwegian krone (NOK)",
        "pay_currency": "NOK",
        "internet_domain": ".no",
        "tax_authority_name": "Norwegian Tax Administration (Skatteetaten)",
        "social_security_authority_name": "Norwegian Labour and Welfare Administration (NAV)",
    },
    {
        "country_name": "Panama",
        "official_name": "Republic of Panama",
        "slug": "panama",
        "iso_code": "PA",
        "region": "North America",
        "capital": "Panama City",
        "currency": "Panamanian balboa (PAB); United States dollar (USD)",
        "pay_currency": "PAB / USD",
        "internet_domain": ".pa",
        "tax_authority_name": "General Directorate of Revenue (DGI)",
        "social_security_authority_name": "Social Security Fund (CSS)",
    },
    {
        "country_name": "Paraguay",
        "official_name": "Republic of Paraguay",
        "slug": "paraguay",
        "iso_code": "PY",
        "region": "South America",
        "capital": "Asuncion",
        "currency": "Paraguayan guarani (PYG)",
        "pay_currency": "PYG",
        "internet_domain": ".py",
        "tax_authority_name": "National Directorate of Tax Revenue (DNIT)",
        "social_security_authority_name": "Social Security Institute (IPS)",
    },
    {
        "country_name": "Peru",
        "official_name": "Republic of Peru",
        "slug": "peru",
        "iso_code": "PE",
        "region": "South America",
        "capital": "Lima",
        "currency": "Peruvian sol (PEN)",
        "pay_currency": "PEN",
        "internet_domain": ".pe",
        "tax_authority_name": "National Superintendency of Customs and Tax Administration (SUNAT)",
        "social_security_authority_name": "EsSalud; Office of Pension Normalization (ONP)",
        "authority_note": "Peru payroll social-insurance and public-pension administration sit with separate institutions.",
    },
    {
        "country_name": "Philippines",
        "official_name": "Republic of the Philippines",
        "slug": "philippines",
        "iso_code": "PH",
        "region": "Asia-Pacific",
        "capital": "Manila",
        "currency": "Philippine peso (PHP)",
        "pay_currency": "PHP",
        "internet_domain": ".ph",
        "tax_authority_name": "Bureau of Internal Revenue (BIR)",
        "social_security_authority_name": "Social Security System (SSS); PhilHealth; Pag-IBIG Fund",
        "authority_note": "The Philippines runs separate payroll-linked agencies for social security, health insurance, and housing contributions.",
    },
    {
        "country_name": "Poland",
        "official_name": "Republic of Poland",
        "slug": "poland",
        "iso_code": "PL",
        "region": "Europe",
        "capital": "Warsaw",
        "currency": "Polish zloty (PLN)",
        "pay_currency": "PLN",
        "internet_domain": ".pl",
        "tax_authority_name": "National Revenue Administration (KAS)",
        "social_security_authority_name": "Social Insurance Institution (ZUS)",
    },
    {
        "country_name": "Portugal",
        "official_name": "Portuguese Republic",
        "slug": "portugal",
        "iso_code": "PT",
        "region": "Europe",
        "capital": "Lisbon",
        "currency": "Euro (EUR)",
        "pay_currency": "EUR",
        "internet_domain": ".pt",
        "tax_authority_name": "Tax and Customs Authority (AT)",
        "social_security_authority_name": "Social Security (Segurança Social)",
    },
    {
        "country_name": "Romania",
        "official_name": "Romania",
        "slug": "romania",
        "iso_code": "RO",
        "region": "Europe",
        "capital": "Bucharest",
        "currency": "Romanian leu (RON)",
        "pay_currency": "RON",
        "internet_domain": ".ro",
        "tax_authority_name": "National Agency for Fiscal Administration (ANAF)",
        "social_security_authority_name": "National House of Public Pensions (CNPP)",
    },
    {
        "country_name": "Russia",
        "official_name": "Russian Federation",
        "slug": "russia",
        "iso_code": "RU",
        "region": "Europe",
        "capital": "Moscow",
        "currency": "Russian ruble (RUB)",
        "pay_currency": "RUB",
        "internet_domain": ".ru",
        "tax_authority_name": "Federal Tax Service (FTS)",
        "social_security_authority_name": "Social Fund of Russia (SFR)",
    },
    {
        "country_name": "Saudi Arabia",
        "official_name": "Kingdom of Saudi Arabia",
        "slug": "saudi-arabia",
        "iso_code": "SA",
        "region": "Middle East",
        "capital": "Riyadh",
        "currency": "Saudi riyal (SAR)",
        "pay_currency": "SAR",
        "internet_domain": ".sa",
        "tax_authority_name": "Zakat, Tax and Customs Authority (ZATCA)",
        "social_security_authority_name": "General Organization for Social Insurance (GOSI)",
    },
    {
        "country_name": "Singapore",
        "official_name": "Republic of Singapore",
        "slug": "singapore",
        "iso_code": "SG",
        "region": "Asia-Pacific",
        "capital": "Singapore",
        "currency": "Singapore dollar (SGD)",
        "pay_currency": "SGD",
        "internet_domain": ".sg",
        "tax_authority_name": "Inland Revenue Authority of Singapore (IRAS)",
        "social_security_authority_name": "Central Provident Fund Board (CPF)",
    },
    {
        "country_name": "Slovakia",
        "official_name": "Slovak Republic",
        "slug": "slovakia",
        "iso_code": "SK",
        "region": "Europe",
        "capital": "Bratislava",
        "currency": "Euro (EUR)",
        "pay_currency": "EUR",
        "internet_domain": ".sk",
        "tax_authority_name": "Financial Administration of the Slovak Republic",
        "social_security_authority_name": "Social Insurance Agency",
    },
    {
        "country_name": "South Africa",
        "official_name": "Republic of South Africa",
        "slug": "south-africa",
        "iso_code": "ZA",
        "region": "Africa",
        "capital": "Pretoria; Cape Town; Bloemfontein",
        "currency": "South African rand (ZAR)",
        "pay_currency": "ZAR",
        "internet_domain": ".za",
        "tax_authority_name": "South African Revenue Service (SARS)",
        "social_security_authority_name": "Unemployment Insurance Fund (UIF)",
        "tax_year": "1 March to 28/29 February",
        "authority_note": "South Africa payroll registrations can also extend beyond UIF depending on employer activity and compensation schemes.",
    },
    {
        "country_name": "Spain",
        "official_name": "Kingdom of Spain",
        "slug": "spain",
        "iso_code": "ES",
        "region": "Europe",
        "capital": "Madrid",
        "currency": "Euro (EUR)",
        "pay_currency": "EUR",
        "internet_domain": ".es",
        "tax_authority_name": "State Tax Administration Agency (AEAT)",
        "social_security_authority_name": "General Treasury of the Social Security (TGSS)",
    },
    {
        "country_name": "Sweden",
        "official_name": "Kingdom of Sweden",
        "slug": "sweden",
        "iso_code": "SE",
        "region": "Europe",
        "capital": "Stockholm",
        "currency": "Swedish krona (SEK)",
        "pay_currency": "SEK",
        "internet_domain": ".se",
        "tax_authority_name": "Swedish Tax Agency (Skatteverket)",
        "social_security_authority_name": "Swedish Social Insurance Agency",
    },
    {
        "country_name": "Switzerland",
        "official_name": "Swiss Confederation",
        "slug": "switzerland",
        "iso_code": "CH",
        "region": "Europe",
        "capital": "Bern",
        "currency": "Swiss franc (CHF)",
        "pay_currency": "CHF",
        "internet_domain": ".ch",
        "tax_authority_name": "Swiss Federal Tax Administration (FTA)",
        "social_security_authority_name": "OASI compensation offices",
        "authority_note": "Swiss payroll withholding and social-insurance administration also run through cantonal and compensation-office structures.",
    },
    {
        "country_name": "Turkey",
        "official_name": "Republic of Türkiye",
        "slug": "turkey",
        "iso_code": "TR",
        "region": "Europe",
        "capital": "Ankara",
        "currency": "Turkish lira (TRY)",
        "pay_currency": "TRY",
        "internet_domain": ".tr",
        "tax_authority_name": "Revenue Administration (GIB)",
        "social_security_authority_name": "Social Security Institution (SGK)",
    },
    {
        "country_name": "United Arab Emirates",
        "official_name": "United Arab Emirates",
        "slug": "united-arab-emirates",
        "iso_code": "AE",
        "region": "Middle East",
        "capital": "Abu Dhabi",
        "currency": "UAE dirham (AED)",
        "pay_currency": "AED",
        "internet_domain": ".ae",
        "tax_authority_name": "Federal Tax Authority (FTA)",
        "social_security_authority_name": "General Pension and Social Security Authority (GPSSA)",
        "authority_note": "Federal pension and social-security coverage applies primarily to UAE nationals and GCC nationals covered under the unified protection system.",
    },
    {
        "country_name": "Ukraine",
        "official_name": "Ukraine",
        "slug": "ukraine",
        "iso_code": "UA",
        "region": "Europe",
        "capital": "Kyiv",
        "currency": "Ukrainian hryvnia (UAH)",
        "pay_currency": "UAH",
        "internet_domain": ".ua",
        "tax_authority_name": "State Tax Service of Ukraine",
        "social_security_authority_name": "Pension Fund of Ukraine",
    },
    {
        "country_name": "United States",
        "official_name": "United States of America",
        "slug": "united-states",
        "iso_code": "US",
        "region": "North America",
        "capital": "Washington, D.C.",
        "currency": "United States dollar (USD)",
        "pay_currency": "USD",
        "internet_domain": ".us",
        "tax_authority_name": "Internal Revenue Service (IRS)",
        "social_security_authority_name": "Social Security Administration (SSA)",
        "tax_year": "Calendar year",
    },
    {
        "country_name": "Uruguay",
        "official_name": "Oriental Republic of Uruguay",
        "slug": "uruguay",
        "iso_code": "UY",
        "region": "South America",
        "capital": "Montevideo",
        "currency": "Uruguayan peso (UYU)",
        "pay_currency": "UYU",
        "internet_domain": ".uy",
        "tax_authority_name": "General Tax Directorate (DGI)",
        "social_security_authority_name": "Social Welfare Bank (BPS)",
    },
]


def _build_authority_sentence(entry: dict) -> str:
    items = []
    if entry.get("tax_authority_name"):
        items.append(f"{_('Tax authority')}: {entry['tax_authority_name']}")
    if entry.get("social_security_authority_name"):
        items.append(f"{_('Social security authority')}: {entry['social_security_authority_name']}")
    if not items:
        return _("Verified authority details are still being expanded for this market.")
    return ". ".join(items) + "."


def _build_payroll_points(entry: dict) -> list[dict[str, str]]:
    items: list[dict[str, str]] = []
    if entry.get("tax_authority_name"):
        items.append({"label": _("Tax authority"), "value": entry["tax_authority_name"]})
    if entry.get("social_security_authority_name"):
        items.append({"label": _("Social security authority"), "value": entry["social_security_authority_name"]})
    if entry.get("pay_currency"):
        items.append({"label": _("Payroll currency"), "value": entry["pay_currency"]})
    if entry.get("tax_year"):
        items.append({"label": _("Tax year"), "value": entry["tax_year"]})
    if entry.get("authority_note"):
        items.append({"label": _("Coverage note"), "value": entry["authority_note"]})
    return items


def _build_glance_cards(entry: dict) -> list[dict[str, str]]:
    payroll_essentials = []
    if entry.get("pay_currency"):
        payroll_essentials.append(f"{_('Payroll currency')}: {entry['pay_currency']}")
    if entry.get("tax_year"):
        payroll_essentials.append(f"{_('Tax year')}: {entry['tax_year']}")

    payroll_body = (
        ". ".join(payroll_essentials) + "."
        if payroll_essentials
        else _("Only fields with a verified payroll reference are shown on this profile.")
    )

    return [
        {
            "title": _("Verified authorities"),
            "body": _build_authority_sentence(entry),
            "icon": "fa-building-shield",
        },
        {
            "title": _("Payroll essentials"),
            "body": payroll_body,
            "icon": "fa-file-invoice-dollar",
        },
        {
            "title": "ExactusPay use",
            "body": "Use this profile to align provider review, onboarding, and country-level payroll governance before go-live.",
            "icon": "fa-layer-group",
        },
    ]


def _build_sections(entry: dict) -> list[dict[str, object]]:
    sections = [
        {
            "title": "Authorities and registrations",
            "body": _build_authority_sentence(entry),
            "bullets": [entry["authority_note"]] if entry.get("authority_note") else [],
        },
        {
            "title": "Payroll essentials",
            "body": "Only verified country references are shown here. Unconfirmed items are intentionally left blank rather than inferred.",
            "bullets": [
                f"Payroll currency: {entry['pay_currency']}" if entry.get("pay_currency") else "",
                f"Tax year: {entry['tax_year']}" if entry.get("tax_year") else "",
                f"Internet domain: {entry['internet_domain']}" if entry.get("internet_domain") else "",
            ],
        },
        {
            "title": "How to use this profile",
            "body": "This country page is built as a practical employer reference: authority mapping first, payroll basics second, and implementation detail only where ExactusPay could verify it.",
            "bullets": [
                "Use it to compare provider coverage and local setup requirements.",
                "Escalate live filing or contribution questions against the relevant authority before production payroll.",
            ],
        },
    ]
    for section in sections:
        section["bullets"] = [item for item in section.get("bullets", []) if item]
    return sections


def build_country_record(entry: dict, sort_order: int) -> SimpleNamespace:
    highlights = []
    if entry.get("tax_authority_name"):
        highlights.append("Tax authority mapped")
    if entry.get("social_security_authority_name"):
        highlights.append("Social security authority mapped")
    if entry.get("pay_currency"):
        highlights.append(f"Payroll currency: {entry['pay_currency']}")

    overview = (
        f"This {entry['country_name']} payroll profile focuses on verified employer reference points. "
        "Where ExactusPay could confirm the main tax or social-security body, it is listed below. "
        "Fields without a reliable confirmation are intentionally left blank."
    )

    return SimpleNamespace(
        slug=entry["slug"],
        is_generated_catalog=True,
        iso_code=entry["iso_code"],
        country_name=entry["country_name"],
        official_name=entry.get("official_name", ""),
        hero_intro=(
            f"ExactusPay's {entry['country_name']} payroll guide is structured around verified authorities, "
            "core payroll references, and practical employer review points."
        ),
        overview=overview,
        flag_url=_safe_static(f"img/flags/{entry['iso_code'].lower()}.png"),
        flag_inline_svg="",
        flag_inline_png="",
        capital=entry.get("capital", ""),
        primary_languages=entry.get("primary_languages", ""),
        currency=entry.get("currency", ""),
        population_display=entry.get("population_display", ""),
        timezones=entry.get("timezones", ""),
        dialing_code=entry.get("dialing_code", ""),
        date_format=entry.get("date_format", ""),
        internet_domain=entry.get("internet_domain", ""),
        payroll_frequency=entry.get("payroll_frequency", ""),
        pay_currency=entry.get("pay_currency", ""),
        tax_year=entry.get("tax_year", ""),
        standard_working_week=entry.get("standard_working_week", ""),
        public_holiday_count=entry.get("public_holiday_count", ""),
        statutory_elements=entry.get("statutory_elements", ""),
        employer_contribution_summary=entry.get("employer_contribution_summary", ""),
        termination_notice_summary=entry.get("termination_notice_summary", ""),
        minimum_wage_summary=entry.get("minimum_wage_summary", ""),
        hero_highlights=highlights[:3],
        payroll_data_points=_build_payroll_points(entry),
        glance_cards=_build_glance_cards(entry),
        content_sections=_build_sections(entry),
        employer_considerations=entry.get("employer_considerations", DEFAULT_EMPLOYER_CONSIDERATIONS),
        seo_title=f"{entry['country_name']} Payroll Guide | ExactusPay",
        meta_description=(
            f"Explore ExactusPay's {entry['country_name']} payroll guide with verified authority mapping and core employer reference points."
        ),
        meta_keywords=f"{entry['country_name']} payroll, {entry['country_name']} tax authority, {entry['country_name']} social security, ExactusPay {entry['country_name']}",
        last_reviewed_on=LAST_REVIEWED_ON,
        region=entry["region"],
        tax_authority_name=entry.get("tax_authority_name", ""),
        social_security_authority_name=entry.get("social_security_authority_name", ""),
        authority_note=entry.get("authority_note", ""),
        sort_order=sort_order,
        is_published=True,
    )


COUNTRY_CATALOG = [build_country_record(entry, index * 10) for index, entry in enumerate(RAW_COUNTRIES, start=1)]
COUNTRY_CATALOG_BY_SLUG = {country.slug: country for country in COUNTRY_CATALOG}


def get_country_catalog() -> list[SimpleNamespace]:
    return list(COUNTRY_CATALOG)


def get_country_from_catalog(slug: str) -> SimpleNamespace | None:
    return COUNTRY_CATALOG_BY_SLUG.get(slug)
