from __future__ import annotations


COUNTRY_NAME_MAP = {
    "ar": {
        "AO": "أنغولا",
        "AR": "الأرجنتين",
        "AU": "أستراليا",
        "AT": "النمسا",
        "BE": "بلجيكا",
        "BO": "بوليفيا",
        "BW": "بوتسوانا",
        "BR": "البرازيل",
        "CA": "كندا",
        "CL": "تشيلي",
        "CO": "كولومبيا",
        "CR": "كوستاريكا",
        "DK": "الدنمارك",
        "EC": "الإكوادور",
        "EG": "مصر",
        "ET": "إثيوبيا",
        "EE": "إستونيا",
        "FI": "فنلندا",
        "GB": "المملكة المتحدة",
        "GT": "غواتيمالا",
        "HU": "المجر",
        "IN": "الهند",
        "ID": "إندونيسيا",
        "IE": "أيرلندا",
        "KZ": "كازاخستان",
        "KE": "كينيا",
        "LV": "لاتفيا",
        "LT": "ليتوانيا",
        "MA": "المغرب",
        "MY": "ماليزيا",
        "MT": "مالطا",
        "MX": "المكسيك",
        "NL": "هولندا",
        "NZ": "نيوزيلندا",
        "NG": "نيجيريا",
        "NO": "النرويج",
        "PA": "بنما",
        "PK": "باكستان",
        "PY": "باراغواي",
        "PE": "بيرو",
        "PH": "الفلبين",
        "PL": "بولندا",
        "PT": "البرتغال",
        "RO": "رومانيا",
        "RU": "روسيا",
        "SA": "المملكة العربية السعودية",
        "SG": "سنغافورة",
        "SK": "سلوفاكيا",
        "ZA": "جنوب أفريقيا",
        "ES": "إسبانيا",
        "SE": "السويد",
        "CH": "سويسرا",
        "TR": "تركيا",
        "AE": "الإمارات العربية المتحدة",
        "UA": "أوكرانيا",
        "US": "الولايات المتحدة",
        "UY": "أوروغواي",
    },
    "de": {
        "AO": "Angola",
        "AR": "Argentinien",
        "AU": "Australien",
        "AT": "Oesterreich",
        "BE": "Belgien",
        "BO": "Bolivien",
        "BW": "Botswana",
        "BR": "Brasilien",
        "CA": "Kanada",
        "CL": "Chile",
        "CO": "Kolumbien",
        "CR": "Costa Rica",
        "DK": "Daenemark",
        "EC": "Ecuador",
        "EG": "Aegypten",
        "ET": "Aethiopien",
        "EE": "Estland",
        "FI": "Finnland",
        "GB": "Vereinigtes Koenigreich",
        "GT": "Guatemala",
        "HU": "Ungarn",
        "IN": "Indien",
        "ID": "Indonesien",
        "IE": "Irland",
        "KZ": "Kasachstan",
        "KE": "Kenia",
        "LV": "Lettland",
        "LT": "Litauen",
        "MA": "Marokko",
        "MY": "Malaysia",
        "MT": "Malta",
        "MX": "Mexiko",
        "NL": "Niederlande",
        "NZ": "Neuseeland",
        "NG": "Nigeria",
        "NO": "Norwegen",
        "PA": "Panama",
        "PK": "Pakistan",
        "PY": "Paraguay",
        "PE": "Peru",
        "PH": "Philippinen",
        "PL": "Polen",
        "PT": "Portugal",
        "RO": "Rumaenien",
        "RU": "Russland",
        "SA": "Saudi-Arabien",
        "SG": "Singapur",
        "SK": "Slowakei",
        "ZA": "Suedafrika",
        "ES": "Spanien",
        "SE": "Schweden",
        "CH": "Schweiz",
        "TR": "Tuerkei",
        "AE": "Vereinigte Arabische Emirate",
        "UA": "Ukraine",
        "US": "Vereinigte Staaten",
        "UY": "Uruguay",
    },
    "es": {
        "AO": "Angola",
        "AR": "Argentina",
        "AU": "Australia",
        "AT": "Austria",
        "BE": "Belgica",
        "BO": "Bolivia",
        "BW": "Botsuana",
        "BR": "Brasil",
        "CA": "Canada",
        "CL": "Chile",
        "CO": "Colombia",
        "CR": "Costa Rica",
        "DK": "Dinamarca",
        "EC": "Ecuador",
        "EG": "Egipto",
        "ET": "Etiopia",
        "EE": "Estonia",
        "FI": "Finlandia",
        "GB": "Reino Unido",
        "GT": "Guatemala",
        "HU": "Hungria",
        "IN": "India",
        "ID": "Indonesia",
        "IE": "Irlanda",
        "KZ": "Kazajistan",
        "KE": "Kenia",
        "LV": "Letonia",
        "LT": "Lituania",
        "MA": "Marruecos",
        "MY": "Malasia",
        "MT": "Malta",
        "MX": "Mexico",
        "NL": "Paises Bajos",
        "NZ": "Nueva Zelanda",
        "NG": "Nigeria",
        "NO": "Noruega",
        "PA": "Panama",
        "PK": "Pakistan",
        "PY": "Paraguay",
        "PE": "Peru",
        "PH": "Filipinas",
        "PL": "Polonia",
        "PT": "Portugal",
        "RO": "Rumania",
        "RU": "Rusia",
        "SA": "Arabia Saudita",
        "SG": "Singapur",
        "SK": "Eslovaquia",
        "ZA": "Sudafrica",
        "ES": "Espana",
        "SE": "Suecia",
        "CH": "Suiza",
        "TR": "Turquia",
        "AE": "Emiratos Arabes Unidos",
        "UA": "Ucrania",
        "US": "Estados Unidos",
        "UY": "Uruguay",
    },
    "fr": {
        "AO": "Angola",
        "AR": "Argentine",
        "AU": "Australie",
        "AT": "Autriche",
        "BE": "Belgique",
        "BO": "Bolivie",
        "BW": "Botswana",
        "BR": "Bresil",
        "CA": "Canada",
        "CL": "Chili",
        "CO": "Colombie",
        "CR": "Costa Rica",
        "DK": "Danemark",
        "EC": "Equateur",
        "EG": "Egypte",
        "ET": "Ethiopie",
        "EE": "Estonie",
        "FI": "Finlande",
        "GB": "Royaume-Uni",
        "GT": "Guatemala",
        "HU": "Hongrie",
        "IN": "Inde",
        "ID": "Indonesie",
        "IE": "Irlande",
        "KZ": "Kazakhstan",
        "KE": "Kenya",
        "LV": "Lettonie",
        "LT": "Lituanie",
        "MA": "Maroc",
        "MY": "Malaisie",
        "MT": "Malte",
        "MX": "Mexique",
        "NL": "Pays-Bas",
        "NZ": "Nouvelle-Zelande",
        "NG": "Nigeria",
        "NO": "Norvege",
        "PA": "Panama",
        "PK": "Pakistan",
        "PY": "Paraguay",
        "PE": "Perou",
        "PH": "Philippines",
        "PL": "Pologne",
        "PT": "Portugal",
        "RO": "Roumanie",
        "RU": "Russie",
        "SA": "Arabie saoudite",
        "SG": "Singapour",
        "SK": "Slovaquie",
        "ZA": "Afrique du Sud",
        "ES": "Espagne",
        "SE": "Suede",
        "CH": "Suisse",
        "TR": "Turquie",
        "AE": "Emirats arabes unis",
        "UA": "Ukraine",
        "US": "Etats-Unis",
        "UY": "Uruguay",
    },
    "id": {
        "AO": "Angola",
        "AR": "Argentina",
        "AU": "Australia",
        "AT": "Austria",
        "BE": "Belgia",
        "BO": "Bolivia",
        "BW": "Botswana",
        "BR": "Brasil",
        "CA": "Kanada",
        "CL": "Chili",
        "CO": "Kolombia",
        "CR": "Kosta Rika",
        "DK": "Denmark",
        "EC": "Ekuador",
        "EG": "Mesir",
        "ET": "Etiopia",
        "EE": "Estonia",
        "FI": "Finlandia",
        "GB": "Inggris Raya",
        "GT": "Guatemala",
        "HU": "Hungaria",
        "IN": "India",
        "ID": "Indonesia",
        "IE": "Irlandia",
        "KZ": "Kazakhstan",
        "KE": "Kenya",
        "LV": "Latvia",
        "LT": "Lituania",
        "MA": "Maroko",
        "MY": "Malaysia",
        "MT": "Malta",
        "MX": "Meksiko",
        "NL": "Belanda",
        "NZ": "Selandia Baru",
        "NG": "Nigeria",
        "NO": "Norwegia",
        "PA": "Panama",
        "PK": "Pakistan",
        "PY": "Paraguay",
        "PE": "Peru",
        "PH": "Filipina",
        "PL": "Polandia",
        "PT": "Portugal",
        "RO": "Rumania",
        "RU": "Rusia",
        "SA": "Arab Saudi",
        "SG": "Singapura",
        "SK": "Slowakia",
        "ZA": "Afrika Selatan",
        "ES": "Spanyol",
        "SE": "Swedia",
        "CH": "Swiss",
        "TR": "Turki",
        "AE": "Uni Emirat Arab",
        "UA": "Ukraina",
        "US": "Amerika Serikat",
        "UY": "Uruguay",
    },
    "it": {
        "AO": "Angola",
        "AR": "Argentina",
        "AU": "Australia",
        "AT": "Austria",
        "BE": "Belgio",
        "BO": "Bolivia",
        "BW": "Botswana",
        "BR": "Brasile",
        "CA": "Canada",
        "CL": "Cile",
        "CO": "Colombia",
        "CR": "Costa Rica",
        "DK": "Danimarca",
        "EC": "Ecuador",
        "EG": "Egitto",
        "ET": "Etiopia",
        "EE": "Estonia",
        "FI": "Finlandia",
        "GB": "Regno Unito",
        "GT": "Guatemala",
        "HU": "Ungheria",
        "IN": "India",
        "ID": "Indonesia",
        "IE": "Irlanda",
        "KZ": "Kazakistan",
        "KE": "Kenya",
        "LV": "Lettonia",
        "LT": "Lituania",
        "MA": "Marocco",
        "MY": "Malaysia",
        "MT": "Malta",
        "MX": "Messico",
        "NL": "Paesi Bassi",
        "NZ": "Nuova Zelanda",
        "NG": "Nigeria",
        "NO": "Norvegia",
        "PA": "Panama",
        "PK": "Pakistan",
        "PY": "Paraguay",
        "PE": "Peru",
        "PH": "Filippine",
        "PL": "Polonia",
        "PT": "Portogallo",
        "RO": "Romania",
        "RU": "Russia",
        "SA": "Arabia Saudita",
        "SG": "Singapore",
        "SK": "Slovacchia",
        "ZA": "Sudafrica",
        "ES": "Spagna",
        "SE": "Svezia",
        "CH": "Svizzera",
        "TR": "Turchia",
        "AE": "Emirati Arabi Uniti",
        "UA": "Ucraina",
        "US": "Stati Uniti",
        "UY": "Uruguay",
    },
    "pl": {
        "AO": "Angola",
        "AR": "Argentyna",
        "AU": "Australia",
        "AT": "Austria",
        "BE": "Belgia",
        "BO": "Boliwia",
        "BW": "Botswana",
        "BR": "Brazylia",
        "CA": "Kanada",
        "CL": "Chile",
        "CO": "Kolumbia",
        "CR": "Kostaryka",
        "DK": "Dania",
        "EC": "Ekwador",
        "EG": "Egipt",
        "ET": "Etiopia",
        "EE": "Estonia",
        "FI": "Finlandia",
        "GB": "Wielka Brytania",
        "GT": "Gwatemala",
        "HU": "Wegry",
        "IN": "Indie",
        "ID": "Indonezja",
        "IE": "Irlandia",
        "KZ": "Kazachstan",
        "KE": "Kenia",
        "LV": "Lotwa",
        "LT": "Litwa",
        "MA": "Maroko",
        "MY": "Malezja",
        "MT": "Malta",
        "MX": "Meksyk",
        "NL": "Niderlandy",
        "NZ": "Nowa Zelandia",
        "NG": "Nigeria",
        "NO": "Norwegia",
        "PA": "Panama",
        "PK": "Pakistan",
        "PY": "Paragwaj",
        "PE": "Peru",
        "PH": "Filipiny",
        "PL": "Polska",
        "PT": "Portugalia",
        "RO": "Rumunia",
        "RU": "Rosja",
        "SA": "Arabia Saudyjska",
        "SG": "Singapur",
        "SK": "Slowacja",
        "ZA": "Republika Poludniowej Afryki",
        "ES": "Hiszpania",
        "SE": "Szwecja",
        "CH": "Szwajcaria",
        "TR": "Turcja",
        "AE": "Zjednoczone Emiraty Arabskie",
        "UA": "Ukraina",
        "US": "Stany Zjednoczone",
        "UY": "Urugwaj",
    },
    "pt": {
        "AO": "Angola",
        "AR": "Argentina",
        "AU": "Australia",
        "AT": "Austria",
        "BE": "Belgica",
        "BO": "Bolivia",
        "BW": "Botsuana",
        "BR": "Brasil",
        "CA": "Canada",
        "CL": "Chile",
        "CO": "Colombia",
        "CR": "Costa Rica",
        "DK": "Dinamarca",
        "EC": "Equador",
        "EG": "Egito",
        "ET": "Etiopia",
        "EE": "Estonia",
        "FI": "Finlandia",
        "GB": "Reino Unido",
        "GT": "Guatemala",
        "HU": "Hungria",
        "IN": "India",
        "ID": "Indonesia",
        "IE": "Irlanda",
        "KZ": "Cazaquistao",
        "KE": "Quenia",
        "LV": "Letonia",
        "LT": "Lituania",
        "MA": "Marrocos",
        "MY": "Malasia",
        "MT": "Malta",
        "MX": "Mexico",
        "NL": "Paises Baixos",
        "NZ": "Nova Zelandia",
        "NG": "Nigeria",
        "NO": "Noruega",
        "PA": "Panama",
        "PK": "Paquistao",
        "PY": "Paraguai",
        "PE": "Peru",
        "PH": "Filipinas",
        "PL": "Polonia",
        "PT": "Portugal",
        "RO": "Romenia",
        "RU": "Russia",
        "SA": "Arabia Saudita",
        "SG": "Singapura",
        "SK": "Eslovaquia",
        "ZA": "Africa do Sul",
        "ES": "Espanha",
        "SE": "Suecia",
        "CH": "Suica",
        "TR": "Turquia",
        "AE": "Emirados Arabes Unidos",
        "UA": "Ucrania",
        "US": "Estados Unidos",
        "UY": "Uruguai",
    },
    "ru": {
        "AO": "Ангола",
        "AR": "Аргентина",
        "AU": "Австралия",
        "AT": "Австрия",
        "BE": "Бельгия",
        "BO": "Боливия",
        "BW": "Ботсвана",
        "BR": "Бразилия",
        "CA": "Канада",
        "CL": "Чили",
        "CO": "Колумбия",
        "CR": "Коста-Рика",
        "DK": "Дания",
        "EC": "Эквадор",
        "EG": "Египет",
        "ET": "Эфиопия",
        "EE": "Эстония",
        "FI": "Финляндия",
        "GB": "Великобритания",
        "GT": "Гватемала",
        "HU": "Венгрия",
        "IN": "Индия",
        "ID": "Индонезия",
        "IE": "Ирландия",
        "KZ": "Казахстан",
        "KE": "Кения",
        "LV": "Латвия",
        "LT": "Литва",
        "MA": "Марокко",
        "MY": "Малайзия",
        "MT": "Мальта",
        "MX": "Мексика",
        "NL": "Нидерланды",
        "NZ": "Новая Зеландия",
        "NG": "Нигерия",
        "NO": "Норвегия",
        "PA": "Панама",
        "PK": "Пакистан",
        "PY": "Парагвай",
        "PE": "Перу",
        "PH": "Филиппины",
        "PL": "Польша",
        "PT": "Португалия",
        "RO": "Румыния",
        "RU": "Россия",
        "SA": "Саудовская Аравия",
        "SG": "Сингапур",
        "SK": "Словакия",
        "ZA": "Южная Африка",
        "ES": "Испания",
        "SE": "Швеция",
        "CH": "Швейцария",
        "TR": "Турция",
        "AE": "Объединенные Арабские Эмираты",
        "UA": "Украина",
        "US": "Соединенные Штаты",
        "UY": "Уругвай",
    },
    "sw": {
        "AO": "Angola",
        "AR": "Ajentina",
        "AU": "Australia",
        "AT": "Austria",
        "BE": "Ubelgiji",
        "BO": "Bolivia",
        "BW": "Botswana",
        "BR": "Brazil",
        "CA": "Kanada",
        "CL": "Chile",
        "CO": "Kolombia",
        "CR": "Kosta Rika",
        "DK": "Denmaki",
        "EC": "Ekuado",
        "EG": "Misri",
        "ET": "Ethiopia",
        "EE": "Estonia",
        "FI": "Ufini",
        "GB": "Uingereza",
        "GT": "Guatemala",
        "HU": "Hungaria",
        "IN": "India",
        "ID": "Indonesia",
        "IE": "Ayalandi",
        "KZ": "Kazakhstan",
        "KE": "Kenya",
        "LV": "Latvia",
        "LT": "Lithuania",
        "MA": "Moroko",
        "MY": "Malaysia",
        "MT": "Malta",
        "MX": "Meksiko",
        "NL": "Uholanzi",
        "NZ": "Nyuzilandi",
        "NG": "Nigeria",
        "NO": "Norwe",
        "PA": "Panama",
        "PK": "Pakistan",
        "PY": "Paraguay",
        "PE": "Peru",
        "PH": "Ufilipino",
        "PL": "Polandi",
        "PT": "Ureno",
        "RO": "Romania",
        "RU": "Urusi",
        "SA": "Saudi Arabia",
        "SG": "Singapore",
        "SK": "Slovakia",
        "ZA": "Afrika Kusini",
        "ES": "Uhispania",
        "SE": "Uswidi",
        "CH": "Uswisi",
        "TR": "Uturuki",
        "AE": "Falme za Kiarabu",
        "UA": "Ukraine",
        "US": "Marekani",
        "UY": "Uruguay",
    },
    "th": {
        "AO": "แองโกลา",
        "AR": "อาร์เจนตินา",
        "AU": "ออสเตรเลีย",
        "AT": "ออสเตรีย",
        "BE": "เบลเยียม",
        "BO": "โบลิเวีย",
        "BW": "บอตสวานา",
        "BR": "บราซิล",
        "CA": "แคนาดา",
        "CL": "ชิลี",
        "CO": "โคลอมเบีย",
        "CR": "คอสตาริกา",
        "DK": "เดนมาร์ก",
        "EC": "เอกวาดอร์",
        "EG": "อียิปต์",
        "ET": "เอธิโอเปีย",
        "EE": "เอสโตเนีย",
        "FI": "ฟินแลนด์",
        "GB": "สหราชอาณาจักร",
        "GT": "กัวเตมาลา",
        "HU": "ฮังการี",
        "IN": "อินเดีย",
        "ID": "อินโดนีเซีย",
        "IE": "ไอร์แลนด์",
        "KZ": "คาซัคสถาน",
        "KE": "เคนยา",
        "LV": "ลัตเวีย",
        "LT": "ลิทัวเนีย",
        "MA": "โมร็อกโก",
        "MY": "มาเลเซีย",
        "MT": "มอลตา",
        "MX": "เม็กซิโก",
        "NL": "เนเธอร์แลนด์",
        "NZ": "นิวซีแลนด์",
        "NG": "ไนจีเรีย",
        "NO": "นอร์เวย์",
        "PA": "ปานามา",
        "PK": "ปากีสถาน",
        "PY": "ปารากวัย",
        "PE": "เปรู",
        "PH": "ฟิลิปปินส์",
        "PL": "โปแลนด์",
        "PT": "โปรตุเกส",
        "RO": "โรมาเนีย",
        "RU": "รัสเซีย",
        "SA": "ซาอุดีอาระเบีย",
        "SG": "สิงคโปร์",
        "SK": "สโลวาเกีย",
        "ZA": "แอฟริกาใต้",
        "ES": "สเปน",
        "SE": "สวีเดน",
        "CH": "สวิตเซอร์แลนด์",
        "TR": "ตุรกี",
        "AE": "สหรัฐอาหรับเอมิเรตส์",
        "UA": "ยูเครน",
        "US": "สหรัฐอเมริกา",
        "UY": "อุรุกวัย",
    },
}


OFFICIAL_NAME_MAP = {
    "ar": {
        "AO": "جمهورية أنغولا",
        "AR": "الجمهورية الأرجنتينية",
        "AU": "كومنولث أستراليا",
        "AT": "جمهورية النمسا",
        "BE": "مملكة بلجيكا",
        "BO": "دولة بوليفيا المتعددة القوميات",
        "BW": "جمهورية بوتسوانا",
        "BR": "جمهورية البرازيل الاتحادية",
        "CA": "كندا",
        "CL": "جمهورية تشيلي",
        "CO": "جمهورية كولومبيا",
        "CR": "جمهورية كوستاريكا",
        "DK": "مملكة الدنمارك",
        "EC": "جمهورية الإكوادور",
        "EG": "جمهورية مصر العربية",
        "ET": "جمهورية إثيوبيا الديمقراطية الفيدرالية",
        "EE": "جمهورية إستونيا",
        "FI": "جمهورية فنلندا",
        "GB": "المملكة المتحدة لبريطانيا العظمى وأيرلندا الشمالية",
        "GT": "جمهورية غواتيمالا",
        "HU": "المجر",
        "IN": "جمهورية الهند",
        "ID": "جمهورية إندونيسيا",
        "IE": "أيرلندا",
        "KZ": "جمهورية كازاخستان",
        "KE": "جمهورية كينيا",
        "LV": "جمهورية لاتفيا",
        "LT": "جمهورية ليتوانيا",
        "MA": "مملكة المغرب",
        "MY": "ماليزيا",
        "MT": "جمهورية مالطا",
        "MX": "الولايات المكسيكية المتحدة",
        "NL": "مملكة هولندا",
        "NZ": "نيوزيلندا",
        "NG": "جمهورية نيجيريا الاتحادية",
        "NO": "مملكة النرويج",
        "PA": "جمهورية بنما",
        "PK": "جمهورية باكستان الإسلامية",
        "PY": "جمهورية باراغواي",
        "PE": "جمهورية بيرو",
        "PH": "جمهورية الفلبين",
        "PL": "جمهورية بولندا",
        "PT": "الجمهورية البرتغالية",
        "RO": "رومانيا",
        "RU": "الاتحاد الروسي",
        "SA": "المملكة العربية السعودية",
        "SG": "جمهورية سنغافورة",
        "SK": "الجمهورية السلوفاكية",
        "ZA": "جمهورية جنوب أفريقيا",
        "ES": "مملكة إسبانيا",
        "SE": "مملكة السويد",
        "CH": "الاتحاد السويسري",
        "TR": "جمهورية تركيا",
        "AE": "الإمارات العربية المتحدة",
        "UA": "أوكرانيا",
        "US": "الولايات المتحدة الأمريكية",
        "UY": "جمهورية الأوروغواي الشرقية",
    },
    "de": {
        "AO": "Republik Angola",
        "AR": "Argentinische Republik",
        "AU": "Australischer Bund",
        "AT": "Republik Oesterreich",
        "BE": "Koenigreich Belgien",
        "BO": "Plurinationaler Staat Bolivien",
        "BW": "Republik Botswana",
        "BR": "Foederative Republik Brasilien",
        "CA": "Kanada",
        "CL": "Republik Chile",
        "CO": "Republik Kolumbien",
        "CR": "Republik Costa Rica",
        "DK": "Koenigreich Daenemark",
        "EC": "Republik Ecuador",
        "EG": "Arabische Republik Aegypten",
        "ET": "Demokratische Bundesrepublik Aethiopien",
        "EE": "Republik Estland",
        "FI": "Republik Finnland",
        "GB": "Vereinigtes Koenigreich Grossbritannien und Nordirland",
        "GT": "Republik Guatemala",
        "HU": "Ungarn",
        "IN": "Republik Indien",
        "ID": "Republik Indonesien",
        "IE": "Irland",
        "KZ": "Republik Kasachstan",
        "KE": "Republik Kenia",
        "LV": "Republik Lettland",
        "LT": "Republik Litauen",
        "MA": "Koenigreich Marokko",
        "MY": "Malaysia",
        "MT": "Republik Malta",
        "MX": "Vereinigte Mexikanische Staaten",
        "NL": "Koenigreich der Niederlande",
        "NZ": "Neuseeland",
        "NG": "Bundesrepublik Nigeria",
        "NO": "Koenigreich Norwegen",
        "PA": "Republik Panama",
        "PK": "Islamische Republik Pakistan",
        "PY": "Republik Paraguay",
        "PE": "Republik Peru",
        "PH": "Republik der Philippinen",
        "PL": "Republik Polen",
        "PT": "Portugiesische Republik",
        "RO": "Rumaenien",
        "RU": "Russische Foederation",
        "SA": "Koenigreich Saudi-Arabien",
        "SG": "Republik Singapur",
        "SK": "Slowakische Republik",
        "ZA": "Republik Suedafrika",
        "ES": "Koenigreich Spanien",
        "SE": "Koenigreich Schweden",
        "CH": "Schweizerische Eidgenossenschaft",
        "TR": "Republik Tuerkei",
        "AE": "Vereinigte Arabische Emirate",
        "UA": "Ukraine",
        "US": "Vereinigte Staaten von Amerika",
        "UY": "Orientalische Republik Uruguay",
    },
    "es": {
        "AO": "Republica de Angola",
        "AR": "Republica Argentina",
        "AU": "Mancomunidad de Australia",
        "AT": "Republica de Austria",
        "BE": "Reino de Belgica",
        "BO": "Estado Plurinacional de Bolivia",
        "BW": "Republica de Botsuana",
        "BR": "Republica Federativa del Brasil",
        "CA": "Canada",
        "CL": "Republica de Chile",
        "CO": "Republica de Colombia",
        "CR": "Republica de Costa Rica",
        "DK": "Reino de Dinamarca",
        "EC": "Republica del Ecuador",
        "EG": "Republica Arabe de Egipto",
        "ET": "Republica Democratica Federal de Etiopia",
        "EE": "Republica de Estonia",
        "FI": "Republica de Finlandia",
        "GB": "Reino Unido de Gran Bretana e Irlanda del Norte",
        "GT": "Republica de Guatemala",
        "HU": "Hungria",
        "IN": "Republica de la India",
        "ID": "Republica de Indonesia",
        "IE": "Irlanda",
        "KZ": "Republica de Kazajistan",
        "KE": "Republica de Kenia",
        "LV": "Republica de Letonia",
        "LT": "Republica de Lituania",
        "MA": "Reino de Marruecos",
        "MY": "Malasia",
        "MT": "Republica de Malta",
        "MX": "Estados Unidos Mexicanos",
        "NL": "Reino de los Paises Bajos",
        "NZ": "Nueva Zelanda",
        "NG": "Republica Federal de Nigeria",
        "NO": "Reino de Noruega",
        "PA": "Republica de Panama",
        "PK": "Republica Islamica de Pakistan",
        "PY": "Republica del Paraguay",
        "PE": "Republica del Peru",
        "PH": "Republica de Filipinas",
        "PL": "Republica de Polonia",
        "PT": "Republica Portuguesa",
        "RO": "Rumania",
        "RU": "Federacion de Rusia",
        "SA": "Reino de Arabia Saudita",
        "SG": "Republica de Singapur",
        "SK": "Republica Eslovaca",
        "ZA": "Republica de Sudafrica",
        "ES": "Reino de Espana",
        "SE": "Reino de Suecia",
        "CH": "Confederacion Suiza",
        "TR": "Republica de Turquia",
        "AE": "Emiratos Arabes Unidos",
        "UA": "Ucrania",
        "US": "Estados Unidos de America",
        "UY": "Republica Oriental del Uruguay",
    },
    "fr": {
        "AO": "Republique d'Angola",
        "AR": "Republique argentine",
        "AU": "Commonwealth d'Australie",
        "AT": "Republique d'Autriche",
        "BE": "Royaume de Belgique",
        "BO": "Etat plurinational de Bolivie",
        "BW": "Republique du Botswana",
        "BR": "Republique federative du Bresil",
        "CA": "Canada",
        "CL": "Republique du Chili",
        "CO": "Republique de Colombie",
        "CR": "Republique du Costa Rica",
        "DK": "Royaume du Danemark",
        "EC": "Republique de l'Equateur",
        "EG": "Republique arabe d'Egypte",
        "ET": "Republique democratique federale d'Ethiopie",
        "EE": "Republique d'Estonie",
        "FI": "Republique de Finlande",
        "GB": "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord",
        "GT": "Republique du Guatemala",
        "HU": "Hongrie",
        "IN": "Republique de l'Inde",
        "ID": "Republique d'Indonesie",
        "IE": "Irlande",
        "KZ": "Republique du Kazakhstan",
        "KE": "Republique du Kenya",
        "LV": "Republique de Lettonie",
        "LT": "Republique de Lituanie",
        "MA": "Royaume du Maroc",
        "MY": "Malaisie",
        "MT": "Republique de Malte",
        "MX": "Etats-Unis mexicains",
        "NL": "Royaume des Pays-Bas",
        "NZ": "Nouvelle-Zelande",
        "NG": "Republique federale du Nigeria",
        "NO": "Royaume de Norvege",
        "PA": "Republique du Panama",
        "PK": "Republique islamique du Pakistan",
        "PY": "Republique du Paraguay",
        "PE": "Republique du Perou",
        "PH": "Republique des Philippines",
        "PL": "Republique de Pologne",
        "PT": "Republique portugaise",
        "RO": "Roumanie",
        "RU": "Federation de Russie",
        "SA": "Royaume d'Arabie saoudite",
        "SG": "Republique de Singapour",
        "SK": "Republique slovaque",
        "ZA": "Republique d'Afrique du Sud",
        "ES": "Royaume d'Espagne",
        "SE": "Royaume de Suede",
        "CH": "Confederation suisse",
        "TR": "Republique de Turquie",
        "AE": "Emirats arabes unis",
        "UA": "Ukraine",
        "US": "Etats-Unis d'Amerique",
        "UY": "Republique orientale de l'Uruguay",
    },
    "id": {
        "AO": "Republik Angola",
        "AR": "Republik Argentina",
        "AU": "Persemakmuran Australia",
        "AT": "Republik Austria",
        "BE": "Kerajaan Belgia",
        "BO": "Negara Plurinasional Bolivia",
        "BW": "Republik Botswana",
        "BR": "Republik Federatif Brasil",
        "CA": "Kanada",
        "CL": "Republik Chili",
        "CO": "Republik Kolombia",
        "CR": "Republik Kosta Rika",
        "DK": "Kerajaan Denmark",
        "EC": "Republik Ekuador",
        "EG": "Republik Arab Mesir",
        "ET": "Republik Demokratik Federal Etiopia",
        "EE": "Republik Estonia",
        "FI": "Republik Finlandia",
        "GB": "Kerajaan Bersatu Britania Raya dan Irlandia Utara",
        "GT": "Republik Guatemala",
        "HU": "Hungaria",
        "IN": "Republik India",
        "ID": "Republik Indonesia",
        "IE": "Irlandia",
        "KZ": "Republik Kazakhstan",
        "KE": "Republik Kenya",
        "LV": "Republik Latvia",
        "LT": "Republik Lituania",
        "MA": "Kerajaan Maroko",
        "MY": "Malaysia",
        "MT": "Republik Malta",
        "MX": "Amerika Serikat Meksiko",
        "NL": "Kerajaan Belanda",
        "NZ": "Selandia Baru",
        "NG": "Republik Federal Nigeria",
        "NO": "Kerajaan Norwegia",
        "PA": "Republik Panama",
        "PK": "Republik Islam Pakistan",
        "PY": "Republik Paraguay",
        "PE": "Republik Peru",
        "PH": "Republik Filipina",
        "PL": "Republik Polandia",
        "PT": "Republik Portugal",
        "RO": "Rumania",
        "RU": "Federasi Rusia",
        "SA": "Kerajaan Arab Saudi",
        "SG": "Republik Singapura",
        "SK": "Republik Slowakia",
        "ZA": "Republik Afrika Selatan",
        "ES": "Kerajaan Spanyol",
        "SE": "Kerajaan Swedia",
        "CH": "Konfederasi Swiss",
        "TR": "Republik Turki",
        "AE": "Uni Emirat Arab",
        "UA": "Ukraina",
        "US": "Amerika Serikat",
        "UY": "Republik Oriental Uruguay",
    },
    "it": {
        "AO": "Repubblica dell'Angola",
        "AR": "Repubblica Argentina",
        "AU": "Commonwealth dell'Australia",
        "AT": "Repubblica d'Austria",
        "BE": "Regno del Belgio",
        "BO": "Stato Plurinazionale della Bolivia",
        "BW": "Repubblica del Botswana",
        "BR": "Repubblica Federativa del Brasile",
        "CA": "Canada",
        "CL": "Repubblica del Cile",
        "CO": "Repubblica di Colombia",
        "CR": "Repubblica di Costa Rica",
        "DK": "Regno di Danimarca",
        "EC": "Repubblica dell'Ecuador",
        "EG": "Repubblica Araba d'Egitto",
        "ET": "Repubblica Democratica Federale d'Etiopia",
        "EE": "Repubblica di Estonia",
        "FI": "Repubblica di Finlandia",
        "GB": "Regno Unito di Gran Bretagna e Irlanda del Nord",
        "GT": "Repubblica del Guatemala",
        "HU": "Ungheria",
        "IN": "Repubblica dell'India",
        "ID": "Repubblica di Indonesia",
        "IE": "Irlanda",
        "KZ": "Repubblica del Kazakistan",
        "KE": "Repubblica del Kenya",
        "LV": "Repubblica di Lettonia",
        "LT": "Repubblica di Lituania",
        "MA": "Regno del Marocco",
        "MY": "Malaysia",
        "MT": "Repubblica di Malta",
        "MX": "Stati Uniti Messicani",
        "NL": "Regno dei Paesi Bassi",
        "NZ": "Nuova Zelanda",
        "NG": "Repubblica Federale della Nigeria",
        "NO": "Regno di Norvegia",
        "PA": "Repubblica di Panama",
        "PK": "Repubblica Islamica del Pakistan",
        "PY": "Repubblica del Paraguay",
        "PE": "Repubblica del Peru",
        "PH": "Repubblica delle Filippine",
        "PL": "Repubblica di Polonia",
        "PT": "Repubblica Portoghese",
        "RO": "Romania",
        "RU": "Federazione Russa",
        "SA": "Regno dell'Arabia Saudita",
        "SG": "Repubblica di Singapore",
        "SK": "Repubblica Slovacca",
        "ZA": "Repubblica del Sudafrica",
        "ES": "Regno di Spagna",
        "SE": "Regno di Svezia",
        "CH": "Confederazione Svizzera",
        "TR": "Repubblica di Turchia",
        "AE": "Emirati Arabi Uniti",
        "UA": "Ucraina",
        "US": "Stati Uniti d'America",
        "UY": "Repubblica Orientale dell'Uruguay",
    },
    "pl": {
        "AO": "Republika Angoli",
        "AR": "Republika Argentynska",
        "AU": "Wspolnota Australii",
        "AT": "Republika Austrii",
        "BE": "Krolestwo Belgii",
        "BO": "Wielonarodowe Panstwo Boliwia",
        "BW": "Republika Botswany",
        "BR": "Federacyjna Republika Brazylii",
        "CA": "Kanada",
        "CL": "Republika Chile",
        "CO": "Republika Kolumbii",
        "CR": "Republika Kostaryki",
        "DK": "Krolestwo Danii",
        "EC": "Republika Ekwadoru",
        "EG": "Arabska Republika Egiptu",
        "ET": "Federalna Demokratyczna Republika Etiopii",
        "EE": "Republika Estonii",
        "FI": "Republika Finlandii",
        "GB": "Zjednoczone Krolestwo Wielkiej Brytanii i Irlandii Polnocnej",
        "GT": "Republika Gwatemali",
        "HU": "Wegry",
        "IN": "Republika Indii",
        "ID": "Republika Indonezji",
        "IE": "Irlandia",
        "KZ": "Republika Kazachstanu",
        "KE": "Republika Kenii",
        "LV": "Republika Lotewska",
        "LT": "Republika Litewska",
        "MA": "Krolestwo Maroka",
        "MY": "Malezja",
        "MT": "Republika Malty",
        "MX": "Stany Zjednoczone Meksyku",
        "NL": "Krolestwo Niderlandow",
        "NZ": "Nowa Zelandia",
        "NG": "Federalna Republika Nigerii",
        "NO": "Krolestwo Norwegii",
        "PA": "Republika Panamy",
        "PK": "Islamska Republika Pakistanu",
        "PY": "Republika Paragwaju",
        "PE": "Republika Peru",
        "PH": "Republika Filipin",
        "PL": "Rzeczpospolita Polska",
        "PT": "Republika Portugalska",
        "RO": "Rumunia",
        "RU": "Federacja Rosyjska",
        "SA": "Krolestwo Arabii Saudyjskiej",
        "SG": "Republika Singapuru",
        "SK": "Republika Slowacka",
        "ZA": "Republika Poludniowej Afryki",
        "ES": "Krolestwo Hiszpanii",
        "SE": "Krolestwo Szwecji",
        "CH": "Konfederacja Szwajcarska",
        "TR": "Republika Turcji",
        "AE": "Zjednoczone Emiraty Arabskie",
        "UA": "Ukraina",
        "US": "Stany Zjednoczone Ameryki",
        "UY": "Wschodnia Republika Urugwaju",
    },
    "pt": {
        "AO": "Republica de Angola",
        "AR": "Republica Argentina",
        "AU": "Comunidade da Australia",
        "AT": "Republica da Austria",
        "BE": "Reino da Belgica",
        "BO": "Estado Plurinacional da Bolivia",
        "BW": "Republica do Botsuana",
        "BR": "Republica Federativa do Brasil",
        "CA": "Canada",
        "CL": "Republica do Chile",
        "CO": "Republica da Colombia",
        "CR": "Republica da Costa Rica",
        "DK": "Reino da Dinamarca",
        "EC": "Republica do Equador",
        "EG": "Republica Arabe do Egito",
        "ET": "Republica Democratica Federal da Etiopia",
        "EE": "Republica da Estonia",
        "FI": "Republica da Finlandia",
        "GB": "Reino Unido da Gra-Bretanha e da Irlanda do Norte",
        "GT": "Republica da Guatemala",
        "HU": "Hungria",
        "IN": "Republica da India",
        "ID": "Republica da Indonesia",
        "IE": "Irlanda",
        "KZ": "Republica do Cazaquistao",
        "KE": "Republica do Quenia",
        "LV": "Republica da Letonia",
        "LT": "Republica da Lituania",
        "MA": "Reino de Marrocos",
        "MY": "Malasia",
        "MT": "Republica de Malta",
        "MX": "Estados Unidos Mexicanos",
        "NL": "Reino dos Paises Baixos",
        "NZ": "Nova Zelandia",
        "NG": "Republica Federal da Nigeria",
        "NO": "Reino da Noruega",
        "PA": "Republica do Panama",
        "PK": "Republica Islamica do Paquistao",
        "PY": "Republica do Paraguai",
        "PE": "Republica do Peru",
        "PH": "Republica das Filipinas",
        "PL": "Republica da Polonia",
        "PT": "Republica Portuguesa",
        "RO": "Romenia",
        "RU": "Federacao Russa",
        "SA": "Reino da Arabia Saudita",
        "SG": "Republica de Singapura",
        "SK": "Republica Eslovaca",
        "ZA": "Republica da Africa do Sul",
        "ES": "Reino de Espanha",
        "SE": "Reino da Suecia",
        "CH": "Confederacao Suica",
        "TR": "Republica da Turquia",
        "AE": "Emirados Arabes Unidos",
        "UA": "Ucrania",
        "US": "Estados Unidos da America",
        "UY": "Republica Oriental do Uruguai",
    },
    "ru": {
        "AO": "Республика Ангола",
        "AR": "Аргентинская Республика",
        "AU": "Австралийский Союз",
        "AT": "Республика Австрия",
        "BE": "Королевство Бельгия",
        "BO": "Многонациональное Государство Боливия",
        "BW": "Республика Ботсвана",
        "BR": "Федеративная Республика Бразилия",
        "CA": "Канада",
        "CL": "Республика Чили",
        "CO": "Республика Колумбия",
        "CR": "Республика Коста-Рика",
        "DK": "Королевство Дания",
        "EC": "Республика Эквадор",
        "EG": "Арабская Республика Египет",
        "ET": "Федеративная Демократическая Республика Эфиопия",
        "EE": "Эстонская Республика",
        "FI": "Финляндская Республика",
        "GB": "Соединенное Королевство Великобритании и Северной Ирландии",
        "GT": "Республика Гватемала",
        "HU": "Венгрия",
        "IN": "Республика Индия",
        "ID": "Республика Индонезия",
        "IE": "Ирландия",
        "KZ": "Республика Казахстан",
        "KE": "Республика Кения",
        "LV": "Латвийская Республика",
        "LT": "Литовская Республика",
        "MA": "Королевство Марокко",
        "MY": "Малайзия",
        "MT": "Республика Мальта",
        "MX": "Мексиканские Соединенные Штаты",
        "NL": "Королевство Нидерландов",
        "NZ": "Новая Зеландия",
        "NG": "Федеративная Республика Нигерия",
        "NO": "Королевство Норвегия",
        "PA": "Республика Панама",
        "PK": "Исламская Республика Пакистан",
        "PY": "Республика Парагвай",
        "PE": "Республика Перу",
        "PH": "Республика Филиппины",
        "PL": "Республика Польша",
        "PT": "Португальская Республика",
        "RO": "Румыния",
        "RU": "Российская Федерация",
        "SA": "Королевство Саудовская Аравия",
        "SG": "Республика Сингапур",
        "SK": "Словацкая Республика",
        "ZA": "Южно-Африканская Республика",
        "ES": "Королевство Испания",
        "SE": "Королевство Швеция",
        "CH": "Швейцарская Конфедерация",
        "TR": "Турецкая Республика",
        "AE": "Объединенные Арабские Эмираты",
        "UA": "Украина",
        "US": "Соединенные Штаты Америки",
        "UY": "Восточная Республика Уругвай",
    },
    "sw": {
        "AO": "Jamhuri ya Angola",
        "AR": "Jamhuri ya Argentina",
        "AU": "Jumuiya ya Madola ya Australia",
        "AT": "Jamhuri ya Austria",
        "BE": "Ufalme wa Ubelgiji",
        "BO": "Dola la Bolivia la Mataifa Mengi",
        "BW": "Jamhuri ya Botswana",
        "BR": "Jamhuri ya Shirikisho ya Brazil",
        "CA": "Kanada",
        "CL": "Jamhuri ya Chile",
        "CO": "Jamhuri ya Kolombia",
        "CR": "Jamhuri ya Kosta Rika",
        "DK": "Ufalme wa Denmaki",
        "EC": "Jamhuri ya Ekuado",
        "EG": "Jamhuri ya Kiarabu ya Misri",
        "ET": "Jamhuri ya Kidemokrasia ya Shirikisho ya Ethiopia",
        "EE": "Jamhuri ya Estonia",
        "FI": "Jamhuri ya Ufini",
        "GB": "Ufalme wa Muungano wa Uingereza na Ireland ya Kaskazini",
        "GT": "Jamhuri ya Guatemala",
        "HU": "Hungaria",
        "IN": "Jamhuri ya India",
        "ID": "Jamhuri ya Indonesia",
        "IE": "Ayalandi",
        "KZ": "Jamhuri ya Kazakhstan",
        "KE": "Jamhuri ya Kenya",
        "LV": "Jamhuri ya Latvia",
        "LT": "Jamhuri ya Lithuania",
        "MA": "Ufalme wa Moroko",
        "MY": "Malaysia",
        "MT": "Jamhuri ya Malta",
        "MX": "Nchi za Muungano wa Meksiko",
        "NL": "Ufalme wa Uholanzi",
        "NZ": "Nyuzilandi",
        "NG": "Jamhuri ya Shirikisho ya Nigeria",
        "NO": "Ufalme wa Norwe",
        "PA": "Jamhuri ya Panama",
        "PK": "Jamhuri ya Kiislamu ya Pakistan",
        "PY": "Jamhuri ya Paraguay",
        "PE": "Jamhuri ya Peru",
        "PH": "Jamhuri ya Ufilipino",
        "PL": "Jamhuri ya Polandi",
        "PT": "Jamhuri ya Ureno",
        "RO": "Romania",
        "RU": "Shirikisho la Urusi",
        "SA": "Ufalme wa Saudi Arabia",
        "SG": "Jamhuri ya Singapore",
        "SK": "Jamhuri ya Slovakia",
        "ZA": "Jamhuri ya Afrika Kusini",
        "ES": "Ufalme wa Uhispania",
        "SE": "Ufalme wa Uswidi",
        "CH": "Shirikisho la Uswisi",
        "TR": "Jamhuri ya Uturuki",
        "AE": "Falme za Kiarabu",
        "UA": "Ukraine",
        "US": "Marekani",
        "UY": "Jamhuri ya Mashariki ya Uruguay",
    },
    "th": {
        "AO": "สาธารณรัฐแองโกลา",
        "AR": "สาธารณรัฐอาร์เจนตินา",
        "AU": "เครือรัฐออสเตรเลีย",
        "AT": "สาธารณรัฐออสเตรีย",
        "BE": "ราชอาณาจักรเบลเยียม",
        "BO": "รัฐพหุชนชาติแห่งโบลิเวีย",
        "BW": "สาธารณรัฐบอตสวานา",
        "BR": "สหพันธ์สาธารณรัฐบราซิล",
        "CA": "แคนาดา",
        "CL": "สาธารณรัฐชิลี",
        "CO": "สาธารณรัฐโคลอมเบีย",
        "CR": "สาธารณรัฐคอสตาริกา",
        "DK": "ราชอาณาจักรเดนมาร์ก",
        "EC": "สาธารณรัฐเอกวาดอร์",
        "EG": "สาธารณรัฐอาหรับอียิปต์",
        "ET": "สหพันธ์สาธารณรัฐประชาธิปไตยเอธิโอเปีย",
        "EE": "สาธารณรัฐเอสโตเนีย",
        "FI": "สาธารณรัฐฟินแลนด์",
        "GB": "สหราชอาณาจักรบริเตนใหญ่และไอร์แลนด์เหนือ",
        "GT": "สาธารณรัฐกัวเตมาลา",
        "HU": "ฮังการี",
        "IN": "สาธารณรัฐอินเดีย",
        "ID": "สาธารณรัฐอินโดนีเซีย",
        "IE": "ไอร์แลนด์",
        "KZ": "สาธารณรัฐคาซัคสถาน",
        "KE": "สาธารณรัฐเคนยา",
        "LV": "สาธารณรัฐลัตเวีย",
        "LT": "สาธารณรัฐลิทัวเนีย",
        "MA": "ราชอาณาจักรโมร็อกโก",
        "MY": "มาเลเซีย",
        "MT": "สาธารณรัฐมอลตา",
        "MX": "สหรัฐเม็กซิโก",
        "NL": "ราชอาณาจักรเนเธอร์แลนด์",
        "NZ": "นิวซีแลนด์",
        "NG": "สหพันธ์สาธารณรัฐไนจีเรีย",
        "NO": "ราชอาณาจักรนอร์เวย์",
        "PA": "สาธารณรัฐปานามา",
        "PK": "สาธารณรัฐอิสลามปากีสถาน",
        "PY": "สาธารณรัฐปารากวัย",
        "PE": "สาธารณรัฐเปรู",
        "PH": "สาธารณรัฐฟิลิปปินส์",
        "PL": "สาธารณรัฐโปแลนด์",
        "PT": "สาธารณรัฐโปรตุเกส",
        "RO": "โรมาเนีย",
        "RU": "สหพันธรัฐรัสเซีย",
        "SA": "ราชอาณาจักรซาอุดีอาระเบีย",
        "SG": "สาธารณรัฐสิงคโปร์",
        "SK": "สาธารณรัฐสโลวัก",
        "ZA": "สาธารณรัฐแอฟริกาใต้",
        "ES": "ราชอาณาจักรสเปน",
        "SE": "ราชอาณาจักรสวีเดน",
        "CH": "สมาพันธรัฐสวิส",
        "TR": "สาธารณรัฐตุรกี",
        "AE": "สหรัฐอาหรับเอมิเรตส์",
        "UA": "ยูเครน",
        "US": "สหรัฐอเมริกา",
        "UY": "สาธารณรัฐตะวันออกอุรุกวัย",
    },
}


REGION_NAME_MAP = {
    "ar": {
        "Africa": "أفريقيا",
        "Asia-Pacific": "آسيا والمحيط الهادئ",
        "Europe": "أوروبا",
        "Middle East": "الشرق الأوسط",
        "North America": "أمريكا الشمالية",
        "South America": "أمريكا الجنوبية",
    },
    "de": {
        "Africa": "Afrika",
        "Asia-Pacific": "Asien-Pazifik",
        "Europe": "Europa",
        "Middle East": "Naher Osten",
        "North America": "Nordamerika",
        "South America": "Suedamerika",
    },
    "es": {
        "Africa": "Africa",
        "Asia-Pacific": "Asia-Pacifico",
        "Europe": "Europa",
        "Middle East": "Oriente Medio",
        "North America": "America del Norte",
        "South America": "America del Sur",
    },
    "fr": {
        "Africa": "Afrique",
        "Asia-Pacific": "Asie-Pacifique",
        "Europe": "Europe",
        "Middle East": "Moyen-Orient",
        "North America": "Amerique du Nord",
        "South America": "Amerique du Sud",
    },
    "id": {
        "Africa": "Afrika",
        "Asia-Pacific": "Asia-Pasifik",
        "Europe": "Eropa",
        "Middle East": "Timur Tengah",
        "North America": "Amerika Utara",
        "South America": "Amerika Selatan",
    },
    "it": {
        "Africa": "Africa",
        "Asia-Pacific": "Asia-Pacifico",
        "Europe": "Europa",
        "Middle East": "Medio Oriente",
        "North America": "Nord America",
        "South America": "Sud America",
    },
    "pl": {
        "Africa": "Afryka",
        "Asia-Pacific": "Azja i Pacyfik",
        "Europe": "Europa",
        "Middle East": "Bliski Wschod",
        "North America": "Ameryka Polnocna",
        "South America": "Ameryka Poludniowa",
    },
    "pt": {
        "Africa": "Africa",
        "Asia-Pacific": "Asia-Pacifico",
        "Europe": "Europa",
        "Middle East": "Medio Oriente",
        "North America": "America do Norte",
        "South America": "America do Sul",
    },
    "ru": {
        "Africa": "Африка",
        "Asia-Pacific": "Азиатско-Тихоокеанский регион",
        "Europe": "Европа",
        "Middle East": "Ближний Восток",
        "North America": "Северная Америка",
        "South America": "Южная Америка",
    },
    "sw": {
        "Africa": "Afrika",
        "Asia-Pacific": "Asia-Pasifiki",
        "Europe": "Ulaya",
        "Middle East": "Mashariki ya Kati",
        "North America": "Amerika Kaskazini",
        "South America": "Amerika Kusini",
    },
    "th": {
        "Africa": "แอฟริกา",
        "Asia-Pacific": "เอเชียแปซิฟิก",
        "Europe": "ยุโรป",
        "Middle East": "ตะวันออกกลาง",
        "North America": "อเมริกาเหนือ",
        "South America": "อเมริกาใต้",
    },
}
