# Generated by Django 5.2.8 on 2026-01-25 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0001_initial'),
        ('elements', '0002_alter_element_element_account_and_more'),
        ('pdcodes', '0002_alter_pdcode_pdcode_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensationcomponent',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elements.element'),
        ),
        migrations.AlterField(
            model_name='compensationcomponent',
            name='pd_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='pdcodes.pdcode', verbose_name='PD Code'),
        ),
    ]
