# Generated by Django 5.2.8 on 2026-01-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0002_alter_compensationcomponent_element_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensationcomponent',
            name='category',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('VARIABLE', 'One-Off Payment')], max_length=20),
        ),
    ]
