# Generated by Django 5.2.8 on 2026-01-14 09:33

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('country', '0001_initial'),
        ('employee', '0001_initial'),
        ('regulations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(help_text='The fiscal year for this payroll', verbose_name='Fiscal Year')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('locked', 'Locked')], default='draft', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, help_text='Optional description of this payroll', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='Locked At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='company.company', verbose_name='Company')),
                ('country', models.ForeignKey(help_text='Country regulations to apply', on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='country.country', verbose_name='Country')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payrolls', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_payrolls', to=settings.AUTH_USER_MODEL, verbose_name='Locked By')),
                ('regulation', models.ForeignKey(help_text='Select the specific regulation version for this fiscal year', on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='regulations.regulations', verbose_name='Regulation Version')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.IntegerField(help_text='Sequential period number within the fiscal year', verbose_name='Period Number')),
                ('name', models.CharField(help_text='e.g., January 2024, Q1 2024, etc.', max_length=100, verbose_name='Period Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('processing_date', models.DateField(help_text='Date when payroll should be processed', verbose_name='Processing Date')),
                ('payment_date', models.DateField(help_text='Date when employees should be paid', verbose_name='Payment Date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('LOCKED', 'Locked'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Status')),
                ('employee_count', models.IntegerField(default=0, verbose_name='Employee Count')),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Gross Amount')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Deductions')),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Net Amount')),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Tax')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Amount')),
                ('apply_regulations', models.BooleanField(default=True, verbose_name='Apply Country Regulations')),
                ('regulation_overrides', models.JSONField(blank=True, default=dict, help_text='JSON overrides for specific regulations', verbose_name='Regulation Overrides')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_periods', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='payroll.payroll', verbose_name='Payroll')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_periods', to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
            ],
            options={
                'verbose_name': 'Payroll Period',
                'verbose_name_plural': 'Payroll Periods',
                'ordering': ['payroll', 'period_number'],
            },
        ),
        migrations.CreateModel(
            name='PayrollExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_type', models.CharField(choices=[('calculation', 'Calculation'), ('approval', 'Approval'), ('payment', 'Payment'), ('reporting', 'Reporting'), ('adjustment', 'Adjustment')], max_length=50, verbose_name='Execution Type')),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=20, verbose_name='Status')),
                ('input_data', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('output_data', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('error_details', models.TextField(blank=True, help_text='Error details if execution failed', verbose_name='Error Details')),
                ('employee_count', models.IntegerField(default=0, verbose_name='Employee Count')),
                ('processing_time', models.DurationField(blank=True, null=True, verbose_name='Processing Time')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_executions', to=settings.AUTH_USER_MODEL, verbose_name='Executed By')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='payroll.payrollperiod', verbose_name='Payroll Period')),
            ],
            options={
                'verbose_name': 'Payroll Execution Log',
                'verbose_name_plural': 'Payroll Execution Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('bonus', 'Bonus'), ('deduction', 'Deduction'), ('allowance', 'Allowance'), ('correction', 'Correction'), ('other', 'Other')], max_length=50, verbose_name='Adjustment Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('affected_employees', models.JSONField(blank=True, default=list, help_text='List of employee IDs affected by this adjustment', verbose_name='Affected Employees')),
                ('regulation_reference', models.CharField(blank=True, help_text='Reference to specific regulation if applicable', max_length=100, verbose_name='Regulation Reference')),
                ('is_applied', models.BooleanField(default=False, verbose_name='Is Applied')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Applied At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied')], default='pending', max_length=20, verbose_name='Status')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='payroll.payrollperiod', verbose_name='Payroll Period')),
            ],
            options={
                'verbose_name': 'Payroll Adjustment',
                'verbose_name_plural': 'Payroll Adjustments',
                'ordering': ['period', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_results', to='employee.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='payroll.payrollperiod')),
            ],
            options={
                'verbose_name': 'Payroll Result',
                'verbose_name_plural': 'Payroll Results',
                'ordering': ['employee'],
            },
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['company', 'fiscal_year'], name='payroll_pay_company_4370be_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['status'], name='payroll_pay_status_465a76_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['created_at'], name='payroll_pay_created_b8460d_idx'),
        ),
        migrations.AddConstraint(
            model_name='payroll',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('company', 'fiscal_year'), name='unique_payroll_per_company_year'),
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['payroll', 'period_number'], name='payroll_pay_payroll_2ef986_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['status'], name='payroll_pay_status_c18070_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['processing_date'], name='payroll_pay_process_328660_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['start_date', 'end_date'], name='payroll_pay_start_d_46a73f_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.UniqueConstraint(fields=('payroll', 'period_number'), name='unique_period_number_per_payroll'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.UniqueConstraint(fields=('payroll', 'start_date', 'end_date'), name='unique_date_range_per_payroll'),
        ),
        migrations.AddIndex(
            model_name='payrollexecutionlog',
            index=models.Index(fields=['period', 'execution_type'], name='payroll_pay_period__0b5888_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollexecutionlog',
            index=models.Index(fields=['status'], name='payroll_pay_status_72b68f_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollexecutionlog',
            index=models.Index(fields=['started_at'], name='payroll_pay_started_5677c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollresult',
            unique_together={('period', 'employee')},
        ),
    ]
