# Generated by Django 5.2.8 on 2026-01-20 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_remove_company_accountant_aca_and_more"),
        ("country", "0001_initial"),
        ("payroll", "0002_alter_payrolladjustment_options_and_more"),
        ("regulations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payrolladjustment",
            options={
                "ordering": ["period", "-created_at"],
                "verbose_name": "Payroll Adjustment",
                "verbose_name_plural": "Payroll Adjustments",
            },
        ),
        migrations.AlterModelOptions(
            name="payrollexecutionlog",
            options={
                "ordering": ["-started_at"],
                "verbose_name": "Payroll Execution Log",
                "verbose_name_plural": "Payroll Execution Logs",
            },
        ),
        migrations.AlterModelOptions(
            name="payrollperiod",
            options={
                "ordering": ["payroll", "period_number"],
                "verbose_name": "Payroll Period",
                "verbose_name_plural": "Payroll Periods",
            },
        ),
        migrations.AlterModelOptions(
            name="payrollresult",
            options={
                "ordering": ["employee"],
                "verbose_name": "Payroll Result",
                "verbose_name_plural": "Payroll Results",
            },
        ),
        migrations.RemoveConstraint(
            model_name="payroll",
            name="unique_payroll_per_company_year",
        ),
        migrations.AddField(
            model_name="payroll",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Locked At"),
        ),
        migrations.AddField(
            model_name="payroll",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locked_payrolls",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Locked By",
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("locked", "Locked"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payrolls",
                to="company.company",
                verbose_name="Company",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="country",
            field=models.ForeignKey(
                help_text="Country regulations to apply",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payrolls",
                to="country.country",
                verbose_name="Country",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_payrolls",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional description of this payroll",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="fiscal_year",
            field=models.IntegerField(
                help_text="The fiscal year for this payroll", verbose_name="Fiscal Year"
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="regulation",
            field=models.ForeignKey(
                help_text="Select the specific regulation version for this fiscal year",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payrolls",
                to="regulations.regulations",
                verbose_name="Regulation Version",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="payrolladjustment",
            name="adjustment_type",
            field=models.CharField(
                choices=[
                    ("bonus", "Bonus"),
                    ("deduction", "Deduction"),
                    ("allowance", "Allowance"),
                    ("correction", "Correction"),
                    ("other", "Other"),
                ],
                max_length=50,
                verbose_name="Adjustment Type",
            ),
        ),
        migrations.AlterField(
            model_name="payrolladjustment",
            name="affected_employees",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of employee IDs affected by this adjustment",
                verbose_name="Affected Employees",
            ),
        ),
        migrations.AlterField(
            model_name="payrolladjustment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="Amount"
            ),
        ),
        migrations.AlterField(
            model_name="payrolladjustment",
            name="applied_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Applied At"
            ),
        ),
        migrations.AlterField(
            model_name="payrolladjustment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="payrolladjustment",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_adjustments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="payrolladjustment",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="payrolladjustment",
            name="is_applied",
            field=models.BooleanField(default=False, verbose_name="Is Applied"),
        ),
        migrations.AlterField(
            model_name="payrolladjustment",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adjustments",
                to="payroll.payrollperiod",
                verbose_name="Payroll Period",
            ),
        ),
        migrations.AlterField(
            model_name="payrolladjustment",
            name="regulation_reference",
            field=models.CharField(
                blank=True,
                help_text="Reference to specific regulation if applicable",
                max_length=100,
                verbose_name="Regulation Reference",
            ),
        ),
        migrations.AlterField(
            model_name="payrolladjustment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("applied", "Applied"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="payrolladjustment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AlterField(
            model_name="payrollexecutionlog",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Completed At"
            ),
        ),
        migrations.AlterField(
            model_name="payrollexecutionlog",
            name="employee_count",
            field=models.IntegerField(default=0, verbose_name="Employee Count"),
        ),
        migrations.AlterField(
            model_name="payrollexecutionlog",
            name="error_details",
            field=models.TextField(
                blank=True,
                help_text="Error details if execution failed",
                verbose_name="Error Details",
            ),
        ),
        migrations.AlterField(
            model_name="payrollexecutionlog",
            name="executed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payroll_executions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Executed By",
            ),
        ),
        migrations.AlterField(
            model_name="payrollexecutionlog",
            name="execution_type",
            field=models.CharField(
                choices=[
                    ("calculation", "Calculation"),
                    ("approval", "Approval"),
                    ("payment", "Payment"),
                    ("reporting", "Reporting"),
                    ("adjustment", "Adjustment"),
                ],
                max_length=50,
                verbose_name="Execution Type",
            ),
        ),
        migrations.AlterField(
            model_name="payrollexecutionlog",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="execution_logs",
                to="payroll.payrollperiod",
                verbose_name="Payroll Period",
            ),
        ),
        migrations.AlterField(
            model_name="payrollexecutionlog",
            name="processing_time",
            field=models.DurationField(
                blank=True, null=True, verbose_name="Processing Time"
            ),
        ),
        migrations.AlterField(
            model_name="payrollexecutionlog",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Started At"),
        ),
        migrations.AlterField(
            model_name="payrollexecutionlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("started", "Started"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="payrollperiod",
            name="apply_regulations",
            field=models.BooleanField(
                default=True, verbose_name="Apply Country Regulations"
            ),
        ),
        migrations.AlterField(
            model_name="payrollperiod",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
        migrations.AlterField(
            model_name="payrollperiod",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_periods",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="payrollperiod",
            name="employee_count",
            field=models.IntegerField(default=0, verbose_name="Employee Count"),
        ),
        migrations.AlterField(
            model_name="payrollperiod",
            name="end_date",
            field=models.DateField(verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="payrollperiod",
            name="name",
            field=models.CharField(
                help_text="e.g., January 2024, Q1 2024, etc.",
                max_length=100,
                verbose_name="Period Name",
            ),
        ),
        migrations.AlterField(
            model_name="payrollperiod",
            name="payment_date",
            field=models.DateField(
                help_text="Date when employees should be paid",
                verbose_name="Payment Date",
            ),
        ),
        migrations.AlterField(
            model_name="payrollperiod",
            name="payroll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periods",
                to="payroll.payroll",
                verbose_name="Payroll",
            ),
        ),
        migrations.AlterField(
            model_name="payrollperiod",
            name="period_number",
            field=models.IntegerField(
                help_text="Sequential period number within the fiscal year",
                verbose_name="Period Number",
            ),
        ),
        migrations.AlterField(
            model_name="payrollperiod",
            name="processed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Processed At"
            ),
        ),
        migrations.AlterField(
            model_name="payrollperiod",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_periods",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Processed By",
            ),
        ),
        migrations.AlterField(
            model_name="payrollperiod",
            name="processing_date",
            field=models.DateField(
                help_text="Date when payroll should be processed",
                verbose_name="Processing Date",
            ),
        ),
        migrations.AlterField(
            model_name="payrollperiod",
            name="regulation_overrides",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON overrides for specific regulations",
                verbose_name="Regulation Overrides",
            ),
        ),
        migrations.AlterField(
            model_name="payrollperiod",
            name="start_date",
            field=models.DateField(verbose_name="Start Date"),
        ),
        migrations.AlterField(
            model_name="payrollperiod",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SCHEDULED", "Scheduled"),
                    ("PROCESSING", "Processing"),
                    ("PROCESSED", "Processed"),
                    ("AWAITING_APPROVAL", "Awaiting Approval"),
                    ("COMPLETED", "Completed"),
                    ("LOCKED", "Locked"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="payrollperiod",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="Total Amount"
            ),
        ),
        migrations.AlterField(
            model_name="payrollperiod",
            name="total_deductions",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="Total Deductions",
            ),
        ),
        migrations.AlterField(
            model_name="payrollperiod",
            name="total_gross",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="Total Gross Amount",
            ),
        ),
        migrations.AlterField(
            model_name="payrollperiod",
            name="total_net",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="Total Net Amount",
            ),
        ),
        migrations.AlterField(
            model_name="payrollperiod",
            name="total_tax",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="Total Tax"
            ),
        ),
        migrations.AlterField(
            model_name="payrollperiod",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated At"),
        ),
        migrations.AddIndex(
            model_name="payroll",
            index=models.Index(
                fields=["company", "fiscal_year"], name="payroll_pay_company_4370be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payroll",
            index=models.Index(fields=["status"], name="payroll_pay_status_465a76_idx"),
        ),
        migrations.AddIndex(
            model_name="payroll",
            index=models.Index(
                fields=["created_at"], name="payroll_pay_created_b8460d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollexecutionlog",
            index=models.Index(
                fields=["period", "execution_type"],
                name="payroll_pay_period__0b5888_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollexecutionlog",
            index=models.Index(fields=["status"], name="payroll_pay_status_72b68f_idx"),
        ),
        migrations.AddIndex(
            model_name="payrollexecutionlog",
            index=models.Index(
                fields=["started_at"], name="payroll_pay_started_5677c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollperiod",
            index=models.Index(
                fields=["payroll", "period_number"],
                name="payroll_pay_payroll_2ef986_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollperiod",
            index=models.Index(fields=["status"], name="payroll_pay_status_c18070_idx"),
        ),
        migrations.AddIndex(
            model_name="payrollperiod",
            index=models.Index(
                fields=["processing_date"], name="payroll_pay_process_328660_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollperiod",
            index=models.Index(
                fields=["start_date", "end_date"], name="payroll_pay_start_d_46a73f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payroll",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "cancelled"), _negated=True),
                fields=("company", "fiscal_year"),
                name="unique_payroll_per_company_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollperiod",
            constraint=models.UniqueConstraint(
                fields=("payroll", "start_date", "end_date"),
                name="unique_date_range_per_payroll",
            ),
        ),
    ]
