# Generated by Django 5.2.8 on 2026-01-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_remove_payrollperiod_unique_period_number_per_payroll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollperiod',
            name='frequency',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Fortnightly', 'Fortnightly'), ('Semi-Monthly', 'Semi-Monthly'), ('Four-weekly', 'Four-weekly'), ('Monthly', 'Monthly')], default='Monthly', help_text='Links to CalculationBase frequency', max_length=20, verbose_name='Frequency'),
        ),
    ]
