# Generated by Django 5.2.8 on 2026-01-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_payrollperiod_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='is_historical',
            field=models.BooleanField(default=False, help_text='Check this if this payroll record is for storing historical data from previous years.', verbose_name='Historical Data Only'),
        ),
        migrations.AlterField(
            model_name='payrollexecutionlog',
            name='execution_type',
            field=models.CharField(choices=[('calculation', 'Calculation'), ('approval', 'Approval'), ('payment', 'Payment'), ('reporting', 'Reporting'), ('adjustment', 'Adjustment'), ('historical_upload', 'Historical Upload')], max_length=50, verbose_name='Execution Type'),
        ),
    ]
