# Generated by Django 5.2.8 on 2025-12-10 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('pdcodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PERMANENT', 'Permanent'), ('VARIABLE', 'Variable')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False, help_text='True once this component has been processed in payroll.')),
                ('processed_period', models.CharField(blank=True, help_text="Payroll period identifier, e.g. '2025-03'.", max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_components', to='employee.employee')),
                ('pd_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compensation_components', to='pdcodes.pdcode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
