# Generated by Django 5.2.8 on 2026-01-14 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elements', '0001_initial'),
        ('employee', '0001_initial'),
        ('pdcodes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('annual', 'Annual'), ('one_time', 'One Time')], default='monthly', max_length=20, verbose_name='Frequency')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for ongoing', null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('processed', models.BooleanField(default=False, verbose_name='Processed')),
                ('processed_period', models.CharField(blank=True, help_text='Period when this component was processed (e.g., 2024-01)', max_length=50, verbose_name='Processed Period')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Reference')),
                ('category', models.CharField(choices=[('PERMANENT', 'Permanent'), ('VARIABLE', 'Variable')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_components', to=settings.AUTH_USER_MODEL)),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='elements.element')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_components', to='employee.employee')),
                ('pd_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='pdcodes.pdcode', verbose_name='PD Code')),
            ],
            options={
                'verbose_name': 'Compensation Component',
                'verbose_name_plural': 'Compensation Components',
                'ordering': ['employee', '-start_date'],
                'indexes': [models.Index(fields=['employee', 'is_active', 'processed'], name='compensatio_employe_d5f908_idx'), models.Index(fields=['start_date', 'end_date'], name='compensatio_start_d_f2b90e_idx')],
            },
        ),
    ]
