# Generated by Django 5.2.8 on 2025-12-18 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0001_initial'),
        ('employee', '0001_initial'),
        ('pdcodes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compensationcomponent',
            options={'ordering': ['employee', '-start_date'], 'verbose_name': 'Compensation Component', 'verbose_name_plural': 'Compensation Components'},
        ),
        migrations.RemoveField(
            model_name='compensationcomponent',
            name='category',
        ),
        migrations.AddField(
            model_name='compensationcomponent',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_components', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compensationcomponent',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='compensationcomponent',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('annual', 'Annual'), ('one_time', 'One Time')], default='monthly', max_length=20, verbose_name='Frequency'),
        ),
        migrations.AddField(
            model_name='compensationcomponent',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='compensationcomponent',
            name='reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='compensationcomponent',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='compensationcomponent',
            name='end_date',
            field=models.DateField(blank=True, help_text='Leave blank for ongoing', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='compensationcomponent',
            name='pd_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='pdcodes.pdcode', verbose_name='PD Code'),
        ),
        migrations.AlterField(
            model_name='compensationcomponent',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Processed'),
        ),
        migrations.AlterField(
            model_name='compensationcomponent',
            name='processed_period',
            field=models.CharField(blank=True, default=1, help_text='Period when this component was processed (e.g., 2024-01)', max_length=50, verbose_name='Processed Period'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compensationcomponent',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AddIndex(
            model_name='compensationcomponent',
            index=models.Index(fields=['employee', 'is_active', 'processed'], name='compensatio_employe_d5f908_idx'),
        ),
        migrations.AddIndex(
            model_name='compensationcomponent',
            index=models.Index(fields=['start_date', 'end_date'], name='compensatio_start_d_f2b90e_idx'),
        ),
    ]
