# Generated by Django 5.2.8 on 2025-12-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0002_alter_compensationcomponent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensationcomponent',
            name='category',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('VARIABLE', 'Variable'), ('DEDUCTION', 'Deduction')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
