# Generated by Django 5.2.8 on 2025-12-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0003_compensationcomponent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensationcomponent',
            name='category',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('VARIABLE', 'Variable')], max_length=20),
        ),
    ]
