# Generated by Django 5.2.8 on 2026-02-13 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0005_company_users_alter_company_agent_full_name_and_more"),
        ("country", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReportType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(
                        help_text="Internal reference, e.g., 'PAYSLIP_STD'",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "is_employee_accessible",
                    models.BooleanField(
                        default=False, help_text="Can employees see this via ESS?"
                    ),
                ),
                (
                    "is_statutory",
                    models.BooleanField(
                        default=False, help_text="Is this a legal requirement?"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.reportcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'UK Modern Blue'", max_length=100
                    ),
                ),
                (
                    "template_file",
                    models.FileField(
                        help_text="Upload the .html file here",
                        upload_to="report_templates/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layouts",
                        to="reports.reporttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Toggle data fields (e.g., Show Bonus: True/False)",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "System Default"),
                            ("COUNTRY", "Country Default"),
                            ("COMPANY", "Company Specific"),
                        ],
                        editable=False,
                        max_length=20,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="country.country",
                    ),
                ),
                (
                    "selected_layout",
                    models.ForeignKey(
                        help_text="The HTML design to use",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reports.reportlayout",
                    ),
                ),
                (
                    "report_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.reporttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Setting",
                "unique_together": {
                    ("company", "report_type"),
                    ("country", "report_type"),
                },
            },
        ),
    ]
