# Generated by Django 5.2.8 on 2026-02-16 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0005_company_users_alter_company_agent_full_name_and_more"),
        ("country", "0001_initial"),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reportconfiguration",
            options={
                "verbose_name": "Report Setting",
                "verbose_name_plural": "Report Settings",
            },
        ),
        migrations.AlterUniqueTogether(
            name="reportconfiguration",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="reportconfiguration",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reportconfiguration",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="reportconfiguration",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_configurations",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="reportconfiguration",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_configurations",
                to="country.country",
            ),
        ),
        migrations.AlterField(
            model_name="reportconfiguration",
            name="data_settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Toggle data fields (e.g., {'show_logo': true, 'mask_bank_account': false})",
            ),
        ),
        migrations.AlterField(
            model_name="reportconfiguration",
            name="level",
            field=models.CharField(
                choices=[
                    ("SYSTEM", "System Default"),
                    ("COUNTRY", "Country Default"),
                    ("COMPANY", "Company Specific"),
                ],
                db_index=True,
                editable=False,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reportconfiguration",
            name="report_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configurations",
                to="reports.reporttype",
            ),
        ),
        migrations.AlterField(
            model_name="reportconfiguration",
            name="selected_layout",
            field=models.ForeignKey(
                blank=True,
                help_text="The HTML design to use",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="configurations",
                to="reports.reportlayout",
            ),
        ),
        migrations.AddIndex(
            model_name="reportconfiguration",
            index=models.Index(
                fields=["report_type", "company"], name="reports_rep_report__adb54b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportconfiguration",
            index=models.Index(
                fields=["report_type", "country"], name="reports_rep_report__41fa43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportconfiguration",
            index=models.Index(
                fields=["report_type", "level"], name="reports_rep_report__2b83e7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reportconfiguration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("company__isnull", False)),
                fields=("report_type", "company"),
                name="uniq_reportcfg_company_per_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportconfiguration",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("company__isnull", True), ("country__isnull", False)
                ),
                fields=("report_type", "country"),
                name="uniq_reportcfg_country_per_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportconfiguration",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("company__isnull", True), ("country__isnull", True)
                ),
                fields=("report_type",),
                name="uniq_reportcfg_system_per_type",
            ),
        ),
    ]
