# Generated by Django 5.2.8 on 2025-11-26 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField()),
                ('effective_date', models.DateField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('archive', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='N', max_length=1, verbose_name='Archive')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulations', to='country.country')),
            ],
            options={
                'verbose_name': 'Regulation',
                'verbose_name_plural': 'Regulations',
                'ordering': ['country__name', '-fiscal_year'],
            },
        ),
    ]
