# Generated by Django 5.2.8 on 2025-11-26 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('country', '0001_initial'),
        ('regulations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_frequency', models.CharField(blank=True, choices=[('Annually', 'Annually'), ('Monthly', 'Monthly'), ('Semi-Monthly', 'Semi-Monthly'), ('Fortnightly', 'Fortnightly'), ('Weekly', 'Weekly')], max_length=15, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.country')),
                ('regulations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regulations.regulations')),
            ],
        ),
    ]
