# Generated by Django 5.2.8 on 2026-01-21 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_payrolladjustment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payrollperiod',
            name='unique_period_number_per_payroll',
        ),
        migrations.RemoveConstraint(
            model_name='payrollperiod',
            name='unique_date_range_per_payroll',
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='is_additional',
            field=models.BooleanField(default=False, help_text='Check this for corrections, bonuses, or off-cycle runs. Allows date overlaps and calculates differences only.', verbose_name='Additional Run'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_additional', False)), fields=('payroll', 'period_number'), name='unique_period_number_per_payroll'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_additional', False)), fields=('payroll', 'start_date', 'end_date'), name='unique_date_range_per_payroll'),
        ),
    ]
