# Generated by Django 5.2.8 on 2025-12-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_payrolladjustment_payrollexecutionlog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={},
        ),
        migrations.AddField(
            model_name='payrolladjustment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
