# Generated by Django 5.2.8 on 2026-01-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_payroll_is_historical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolladjustment',
            name='late_reporting_reason',
            field=models.CharField(blank=True, choices=[('A', 'A - Notional payment: Payment to Expat by 3rd party or overseas employer'), ('B', 'B - Notional payment: Employment related security'), ('C', 'C - Notional payment: Other'), ('D', "D - Payment to  'scheme organiser'"), ('E', 'E - Micro Employer (Temporary relaxation)'), ('F', 'F - No requirement to maintain a Deduction Working Sheet'), ('G', 'G - Reasonable excuse'), ('H', 'H - Correction to earlier submission')], help_text='Only populate if submitting after the payment date.', max_length=1, null=True, verbose_name='Late Reporting Reason'),
        ),
    ]
