# Generated by Django 5.2.8 on 2025-12-15 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_alter_payroll_options_payrolladjustment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollperiod',
            options={'ordering': ['payroll', 'period_number']},
        ),
        migrations.RemoveIndex(
            model_name='payrollperiod',
            name='payroll_pay_start_d_46a73f_idx',
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='apply_regulations',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='employee_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='name',
            field=models.CharField(blank=True, help_text='e.g. January 2024', max_length=100, verbose_name='Period Name'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='payment_date',
            field=models.DateField(verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='processing_date',
            field=models.DateField(verbose_name='Processing Date'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='regulation_overrides',
            field=models.JSONField(blank=True, default=dict, verbose_name='Regulation Overrides'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='total_gross',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='total_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
