# Generated by Django 5.2.8 on 2025-12-16 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_remove_country_fiscal_year_end_and_more'),
        ('employee', '0001_initial'),
        ('payroll', '0007_alter_payrollperiod_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollexecutionlog',
            name='executed_by',
        ),
        migrations.RemoveField(
            model_name='payrollexecutionlog',
            name='period',
        ),
        migrations.AddField(
            model_name='payroll',
            name='completed_periods',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_employees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_periods',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='total_inss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total INSS'),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='total_irrf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total IRRF'),
        ),
        migrations.CreateModel(
            name='PDCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_earning', models.BooleanField(default=True, verbose_name='Is Earning')),
                ('is_deduction', models.BooleanField(default=False, verbose_name='Is Deduction')),
                ('is_tax', models.BooleanField(default=False, verbose_name='Is Tax')),
                ('is_allowance', models.BooleanField(default=False, verbose_name='Is Allowance')),
                ('is_bonus', models.BooleanField(default=False, verbose_name='Is Bonus')),
                ('is_recurring', models.BooleanField(default=True, verbose_name='Recurring')),
                ('requires_tax', models.BooleanField(default=True, verbose_name='Requires Tax Calculation')),
                ('taxable', models.BooleanField(default=True, verbose_name='Taxable')),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Default Amount')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pd_codes', to='country.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'PD Code',
                'verbose_name_plural': 'PD Codes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PeriodEmployeeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_pay', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('inss', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='INSS')),
                ('irrf', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='IRRF')),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('calculation_details', models.JSONField(blank=True, default=dict)),
                ('processed_components', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_results', to='employee.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_results', to='payroll.payrollperiod')),
            ],
            options={
                'verbose_name': 'Period Employee Result',
                'verbose_name_plural': 'Period Employee Results',
                'ordering': ['employee__employee_code'],
                'unique_together': {('period', 'employee')},
            },
        ),
        migrations.DeleteModel(
            name='PayrollAdjustment',
        ),
        migrations.DeleteModel(
            name='PayrollExecutionLog',
        ),
    ]
