# Generated by Django 5.2.8 on 2025-12-18 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_remove_payrollexecutionlog_executed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('bonus', 'Bonus'), ('deduction', 'Deduction'), ('allowance', 'Allowance'), ('correction', 'Correction'), ('other', 'Other')], max_length=50, verbose_name='Adjustment Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('affected_employees', models.JSONField(blank=True, default=list, help_text='List of employee IDs affected by this adjustment', verbose_name='Affected Employees')),
                ('regulation_reference', models.CharField(blank=True, help_text='Reference to specific regulation if applicable', max_length=100, verbose_name='Regulation Reference')),
                ('is_applied', models.BooleanField(default=False, verbose_name='Is Applied')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Applied At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied')], default='pending', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Payroll Adjustment',
                'verbose_name_plural': 'Payroll Adjustments',
                'ordering': ['period', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_type', models.CharField(choices=[('calculation', 'Calculation'), ('approval', 'Approval'), ('payment', 'Payment'), ('reporting', 'Reporting'), ('adjustment', 'Adjustment')], max_length=50, verbose_name='Execution Type')),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=20, verbose_name='Status')),
                ('input_data', models.JSONField(default=dict, help_text='Input parameters for the execution', verbose_name='Input Data')),
                ('output_data', models.JSONField(default=dict, help_text='Output/results from the execution', verbose_name='Output Data')),
                ('error_details', models.TextField(blank=True, help_text='Error details if execution failed', verbose_name='Error Details')),
                ('employee_count', models.IntegerField(default=0, verbose_name='Employee Count')),
                ('processing_time', models.DurationField(blank=True, null=True, verbose_name='Processing Time')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
            ],
            options={
                'verbose_name': 'Payroll Execution Log',
                'verbose_name_plural': 'Payroll Execution Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.RemoveField(
            model_name='pdcode',
            name='country',
        ),
        migrations.AlterUniqueTogether(
            name='periodemployeeresult',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='periodemployeeresult',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='periodemployeeresult',
            name='period',
        ),
        migrations.AlterModelOptions(
            name='payrollperiod',
            options={'ordering': ['payroll', 'period_number'], 'verbose_name': 'Payroll Period', 'verbose_name_plural': 'Payroll Periods'},
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='completed_periods',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='total_employees',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='total_periods',
        ),
        migrations.RemoveField(
            model_name='payrollperiod',
            name='total_inss',
        ),
        migrations.RemoveField(
            model_name='payrollperiod',
            name='total_irrf',
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='apply_regulations',
            field=models.BooleanField(default=True, verbose_name='Apply Country Regulations'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_periods', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='employee_count',
            field=models.IntegerField(default=0, verbose_name='Employee Count'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='name',
            field=models.CharField(help_text='e.g., January 2024, Q1 2024, etc.', max_length=100, verbose_name='Period Name'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='payment_date',
            field=models.DateField(help_text='Date when employees should be paid', verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Processed At'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_periods', to=settings.AUTH_USER_MODEL, verbose_name='Processed By'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='processing_date',
            field=models.DateField(help_text='Date when payroll should be processed', verbose_name='Processing Date'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='regulation_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='JSON overrides for specific regulations', verbose_name='Regulation Overrides'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Deductions'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='total_gross',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Gross Amount'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='total_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Net Amount'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Tax'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddIndex(
            model_name='payrollperiod',
            index=models.Index(fields=['start_date', 'end_date'], name='payroll_pay_start_d_46a73f_idx'),
        ),
        migrations.AddField(
            model_name='payrolladjustment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='payrolladjustment',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='payroll.payrollperiod', verbose_name='Payroll Period'),
        ),
        migrations.AddField(
            model_name='payrollexecutionlog',
            name='executed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_executions', to=settings.AUTH_USER_MODEL, verbose_name='Executed By'),
        ),
        migrations.AddField(
            model_name='payrollexecutionlog',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='payroll.payrollperiod', verbose_name='Payroll Period'),
        ),
        migrations.DeleteModel(
            name='PDCode',
        ),
        migrations.DeleteModel(
            name='PeriodEmployeeResult',
        ),
        migrations.AddIndex(
            model_name='payrollexecutionlog',
            index=models.Index(fields=['period', 'execution_type'], name='payroll_pay_period__0b5888_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollexecutionlog',
            index=models.Index(fields=['status'], name='payroll_pay_status_72b68f_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollexecutionlog',
            index=models.Index(fields=['started_at'], name='payroll_pay_started_5677c0_idx'),
        ),
    ]
