# Generated by Django 5.2.8 on 2026-01-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculationbase", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculationbase",
            name="rounding_base",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("Round up", "Round up"),
                    ("Round down", "Round down"),
                ],
                default="None",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="calculationbase",
            name="rounding_bracket",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("Round up", "Round up"),
                    ("Round down", "Round down"),
                ],
                default="None",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="calculationbase",
            name="rounding_taxed",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("Round up", "Round up"),
                    ("Round down", "Round down"),
                ],
                default="None",
                max_length=15,
            ),
        ),
    ]
