# Generated by Django 5.2.8 on 2026-01-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculationbase', '0003_alter_calculationbase_rounding_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationbase',
            name='base_frequency',
            field=models.CharField(blank=True, choices=[('Weekly', 'Weekly'), ('Fortnightly', 'Fortnightly'), ('Semi-Monthly', 'Semi-Monthly'), ('Four-weekly', 'Four-weekly'), ('Monthly', 'Monthly')], max_length=15, null=True),
        ),
    ]
