# Generated by Django 5.2.8 on 2026-01-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculationbase', '0004_alter_calculationbase_base_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationbase',
            name='rounding_base_decimals',
            field=models.IntegerField(blank=True, default=2, help_text='Decimals'),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='rounding_bracket_decimals',
            field=models.IntegerField(blank=True, default=2, help_text='Decimals'),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='rounding_taxed_decimals',
            field=models.IntegerField(blank=True, default=2, help_text='Decimals'),
        ),
        migrations.AlterField(
            model_name='calculationbase',
            name='rounding_base',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Round', 'Round'), ('Round up', 'Round up'), ('Round down', 'Round down')], default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='calculationbase',
            name='rounding_bracket',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Round', 'Round'), ('Round up', 'Round up'), ('Round down', 'Round down')], default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='calculationbase',
            name='rounding_taxed',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Round', 'Round'), ('Round up', 'Round up'), ('Round down', 'Round down')], default='None', max_length=15),
        ),
    ]
