# Generated by Django 5.2.8 on 2026-01-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculationbase', '0005_calculationbase_rounding_base_decimals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationbase',
            name='rounding_base',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Round up', 'Round up'), ('Round down', 'Round down')], default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='calculationbase',
            name='rounding_base_decimals',
            field=models.IntegerField(default=2, help_text='Decimal places to round the base to'),
        ),
        migrations.AlterField(
            model_name='calculationbase',
            name='rounding_bracket',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Round up', 'Round up'), ('Round down', 'Round down')], default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='calculationbase',
            name='rounding_bracket_decimals',
            field=models.IntegerField(default=2, help_text='Decimal places to round bracket steps'),
        ),
        migrations.AlterField(
            model_name='calculationbase',
            name='rounding_taxed',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Round up', 'Round up'), ('Round down', 'Round down')], default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='calculationbase',
            name='rounding_taxed_decimals',
            field=models.IntegerField(default=2, help_text='Decimal places to round final tax'),
        ),
    ]
