# Generated by Django 5.2.8 on 2026-01-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculationbase', '0006_alter_calculationbase_rounding_base_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationbase',
            name='rounding_bracket',
        ),
        migrations.RemoveField(
            model_name='calculationbase',
            name='rounding_bracket_decimals',
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_dec_00',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_dec_01',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_dec_02',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_dec_03',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_dec_04',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_dec_05',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_dec_06',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_dec_07',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_dec_08',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_dec_09',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_dec_10',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_dec_11',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_dec_12',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_dec_13',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_dec_14',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_dec_15',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_logic_00',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_logic_01',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_logic_02',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_logic_03',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_logic_04',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_logic_05',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_logic_06',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_logic_07',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_logic_08',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_logic_09',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_logic_10',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_logic_11',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_logic_12',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_logic_13',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_logic_14',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_bracket_logic_15',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_dec_00',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_dec_01',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_dec_02',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_dec_03',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_dec_04',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_dec_05',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_dec_06',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_dec_07',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_dec_08',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_dec_09',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_dec_10',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_dec_11',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_dec_12',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_dec_13',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_dec_14',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_dec_15',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_logic_00',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_logic_01',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_logic_02',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_logic_03',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_logic_04',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_logic_05',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_logic_06',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_logic_07',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_logic_08',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_logic_09',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_logic_10',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_logic_11',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_logic_12',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_logic_13',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_logic_14',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='calculationbase',
            name='round_result_logic_15',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='calculationbase',
            name='rounding_base',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='calculationbase',
            name='rounding_base_decimals',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='calculationbase',
            name='rounding_taxed',
            field=models.CharField(blank=True, choices=[('None', 'Standard (Half Up)'), ('Round up', 'Round Up'), ('Round down', 'Round Down')], default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='calculationbase',
            name='rounding_taxed_decimals',
            field=models.IntegerField(default=2),
        ),
    ]
