# Generated by Django 5.2.8 on 2026-01-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='accountant_aca',
        ),
        migrations.RemoveField(
            model_name='company',
            name='accountant_crc',
        ),
        migrations.RemoveField(
            model_name='company',
            name='accountant_cuit',
        ),
        migrations.RemoveField(
            model_name='company',
            name='accountant_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='accountant_tfn',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_structure',
        ),
        migrations.RemoveField(
            model_name='company',
            name='government_id_01',
        ),
        migrations.RemoveField(
            model_name='company',
            name='government_id_02',
        ),
        migrations.RemoveField(
            model_name='company',
            name='government_id_03',
        ),
        migrations.RemoveField(
            model_name='company',
            name='government_id_04',
        ),
        migrations.RemoveField(
            model_name='company',
            name='number_of_employees',
        ),
        migrations.RemoveField(
            model_name='company',
            name='pay_day',
        ),
        migrations.RemoveField(
            model_name='company',
            name='pay_frequency',
        ),
        migrations.RemoveField(
            model_name='company',
            name='standard_work_hours',
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id_01',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 1'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id_02',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 2'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id_03',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 3'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id_04',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 4'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id_05',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 5'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id_06',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 6'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id_07',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 7'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id_08',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 8'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id_09',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 9'),
        ),
    ]
