# Generated by Django 5.2.8 on 2026-01-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_remove_company_accountant_aca_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="agent_full_name",
            field=models.CharField(
                blank=True,
                help_text="Full name for payroll reporting",
                max_length=150,
                null=True,
                verbose_name="Full Name",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="agent_post_code",
            field=models.CharField(
                blank=True,
                help_text="Post code for payroll reporting",
                max_length=20,
                null=True,
                verbose_name="Post Code",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="agent_road_name_1",
            field=models.CharField(
                blank=True,
                help_text="Road name for payroll reporting",
                max_length=150,
                null=True,
                verbose_name="Road Name 1",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="agent_road_name_2",
            field=models.CharField(
                blank=True,
                help_text="Road name for payroll reporting",
                max_length=150,
                null=True,
                verbose_name="Road Name",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="agent_town",
            field=models.CharField(
                blank=True,
                help_text="Road name for payroll reporting",
                max_length=150,
                null=True,
                verbose_name="Town",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="contact",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="contact"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="email",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="email"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="phone",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="telephone"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="website",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="website"
            ),
        ),
    ]
