# Generated by Django 5.2.8 on 2026-02-02 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_clientgroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='accessible_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='agent_full_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='agent_post_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Post Code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='agent_road_name_1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Road Name 1'),
        ),
        migrations.AlterField(
            model_name='company',
            name='agent_road_name_2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Road Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='agent_town',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Town'),
        ),
        migrations.AlterField(
            model_name='company',
            name='rti_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RTI Password'),
        ),
        migrations.AlterField(
            model_name='company',
            name='rti_user_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RTI User ID'),
        ),
    ]
