# Generated by Django 5.2.8 on 2026-01-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_bank_11_employee_bank_12_employee_bank_13_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='employee',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telephone'),
        ),
    ]
