# Generated by Django 5.2.8 on 2026-01-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_email_employee_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='irregular_payment_pattern',
            field=models.BooleanField(default=False, help_text='Check if this employee is a casual worker or on a zero-hours contract (RTI Flag 145).', verbose_name='Irregular Payment Pattern'),
        ),
    ]
