# Generated by Django 5.2.8 on 2026-02-10 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_irregular_payment_pattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(verbose_name='Effective Date')),
                ('pay_frequency', models.CharField(choices=[('Annual', 'Annual'), ('Monthly', 'Monthly'), ('Hourly', 'Hourly')], default='Annual', max_length=20, verbose_name='Pay Frequency')),
                ('currency', models.CharField(default='GBP', help_text='ISO Code (e.g. GBP, USD)', max_length=3, verbose_name='Currency')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('reason', models.CharField(blank=True, help_text='e.g. Merit Increase, Promotion', max_length=100, verbose_name='Reason for Change')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensations', to='employee.employee')),
            ],
            options={
                'verbose_name_plural': 'Compensation History',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
    ]
