# Generated by Django 5.2.11 on 2026-04-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('iso_code', models.CharField(max_length=2, unique=True)),
                ('country_name', models.CharField(max_length=120)),
                ('official_name', models.CharField(blank=True, max_length=180)),
                ('hero_intro', models.TextField()),
                ('overview', models.TextField(blank=True)),
                ('flag_media_path', models.CharField(blank=True, help_text='Relative path inside the ExactusPay media source, e.g. flags/br.svg', max_length=255)),
                ('capital', models.CharField(blank=True, max_length=120)),
                ('primary_languages', models.CharField(blank=True, max_length=180)),
                ('currency', models.CharField(blank=True, max_length=120)),
                ('population_display', models.CharField(blank=True, max_length=120)),
                ('timezones', models.CharField(blank=True, max_length=180)),
                ('dialing_code', models.CharField(blank=True, max_length=32)),
                ('date_format', models.CharField(blank=True, max_length=32)),
                ('internet_domain', models.CharField(blank=True, max_length=32)),
                ('payroll_frequency', models.CharField(blank=True, max_length=120)),
                ('pay_currency', models.CharField(blank=True, max_length=120)),
                ('tax_year', models.CharField(blank=True, max_length=120)),
                ('standard_working_week', models.CharField(blank=True, max_length=120)),
                ('public_holiday_count', models.CharField(blank=True, max_length=120)),
                ('statutory_elements', models.TextField(blank=True)),
                ('employer_contribution_summary', models.TextField(blank=True)),
                ('termination_notice_summary', models.TextField(blank=True)),
                ('minimum_wage_summary', models.CharField(blank=True, max_length=180)),
                ('hero_highlights', models.JSONField(blank=True, default=list)),
                ('payroll_data_points', models.JSONField(blank=True, default=list)),
                ('glance_cards', models.JSONField(blank=True, default=list)),
                ('content_sections', models.JSONField(blank=True, default=list)),
                ('employer_considerations', models.JSONField(blank=True, default=list)),
                ('seo_title', models.CharField(blank=True, max_length=180)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('last_reviewed_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country profile',
                'verbose_name_plural': 'Country profiles',
                'ordering': ['sort_order', 'country_name'],
            },
        ),
    ]
