from datetime import date

from django.db import migrations


def seed_additional_country_profiles(apps, schema_editor):
    CountryProfile = apps.get_model("home", "CountryProfile")

    def build_profile(
        *,
        sort_order,
        slug,
        iso_code,
        country_name,
        official_name,
        capital,
        primary_languages,
        currency,
        population_display,
        timezones,
        dialing_code,
        date_format,
        internet_domain,
        payroll_frequency,
        pay_currency,
        hero_intro,
        overview,
        standard_working_week="",
        tax_year="Calendar year",
    ):
        return {
            "slug": slug,
            "iso_code": iso_code,
            "country_name": country_name,
            "official_name": official_name,
            "hero_intro": hero_intro,
            "overview": overview,
            "flag_media_path": f"flags/{iso_code.lower()}.svg",
            "capital": capital,
            "primary_languages": primary_languages,
            "currency": currency,
            "population_display": population_display,
            "timezones": timezones,
            "dialing_code": dialing_code,
            "date_format": date_format,
            "internet_domain": internet_domain,
            "payroll_frequency": payroll_frequency,
            "pay_currency": pay_currency,
            "tax_year": tax_year,
            "standard_working_week": standard_working_week,
            "statutory_elements": "Configure income tax withholding, social insurance, paid leave, and locally mandated payroll elements in the ExactusPay country layer.",
            "employer_contribution_summary": "Employer cost should be modeled through the live ExactusPay country data source because contribution logic can change over time.",
            "termination_notice_summary": "Notice, severance, and final-pay handling should be reviewed in the local ExactusPay compliance workflow before payroll changes go live.",
            "minimum_wage_summary": "Maintain from the ExactusPay country data feed because minimum wage indicators are time-sensitive.",
            "hero_highlights": [
                payroll_frequency,
                pay_currency,
                "ExactusPay reporting standard",
            ],
            "glance_cards": [
                {
                    "title": "Country-first payroll context",
                    "body": f"{country_name} can be presented with a strong commercial summary first, then deeper payroll intelligence as implementation progresses.",
                    "icon": "fa-earth-africa",
                },
                {
                    "title": "Scalable ExactusPay structure",
                    "body": "The same page design can support buyer education, SEO, and internal payroll reference across many markets.",
                    "icon": "fa-layer-group",
                },
                {
                    "title": "Ready for richer country feeds",
                    "body": "As more country-level payroll metrics become available, this profile can expand without changing layout or route structure.",
                    "icon": "fa-database",
                },
            ],
            "payroll_data_points": [
                {
                    "label": "Typical employer focus",
                    "value": "Clean setup, repeatable payroll approvals, and a reliable path from local outputs to executive reporting.",
                },
                {
                    "label": "ExactusPay implementation use",
                    "value": "Commercial education page today, expandable country intelligence profile as the platform feed deepens.",
                },
            ],
            "content_sections": [
                {
                    "title": "Payroll overview",
                    "body": f"{country_name} is modeled here as a reusable ExactusPay country page: clear market context, key employer facts, and payroll intelligence in one structured format.",
                    "bullets": [
                        "Use the page in commercial conversations and SEO landing flows.",
                        "Add country-specific payroll logic without redesigning the template.",
                    ],
                },
                {
                    "title": "Employment highlights",
                    "body": "The ExactusPay structure is designed to surface the employer questions that usually come first: pay rhythm, payroll ownership, statutory considerations, and reporting consistency.",
                    "bullets": [
                        "Keep local payroll execution connected to one group reporting model.",
                        "Use country-specific notes to reduce implementation ambiguity.",
                    ],
                },
                {
                    "title": "Compliance notes",
                    "body": "This page is an ExactusPay operating and go-to-market layer, not legal advice. Where country rules are time-sensitive, the expectation is that ExactusPay's live country feed or compliance workflow provides the latest detail.",
                },
            ],
            "employer_considerations": [
                "Use this profile to align payroll, HR, finance, and commercial teams on the country narrative.",
                "Feed volatile indicators such as contributions, notice rules, and minimum wage from the live country data source.",
                "Keep the country page stable while the underlying payroll data becomes richer over time.",
            ],
            "seo_title": f"{country_name} Payroll Guide | Country Payroll Intelligence | ExactusPay",
            "meta_description": f"Explore ExactusPay's {country_name} payroll page with employer facts, payroll intelligence, and a scalable country-page structure.",
            "meta_keywords": f"{country_name} payroll, payroll in {country_name}, country payroll page, ExactusPay {country_name}",
            "is_published": True,
            "sort_order": sort_order,
            "last_reviewed_on": date(2026, 4, 14),
        }

    profiles = [
        build_profile(
            sort_order=1,
            slug="angola",
            iso_code="AO",
            country_name="Angola",
            official_name="Republic of Angola",
            capital="Luanda",
            primary_languages="Portuguese",
            currency="Angolan kwanza (AOA)",
            population_display="37M+",
            timezones="UTC+01:00",
            dialing_code="+244",
            date_format="DD/MM/YYYY",
            internet_domain=".ao",
            payroll_frequency="Typically monthly",
            pay_currency="AOA",
            hero_intro="A growing payroll market where employers need a clear local operating model before scale creates friction.",
            overview="The Angola profile is designed for ExactusPay's reusable country-page system: market facts, payroll framing, and a commercially useful summary that can deepen as platform data expands.",
            standard_working_week="Typically around 44 hours",
        ),
        build_profile(
            sort_order=2,
            slug="argentina",
            iso_code="AR",
            country_name="Argentina",
            official_name="Argentine Republic",
            capital="Buenos Aires",
            primary_languages="Spanish",
            currency="Argentine peso (ARS)",
            population_display="46M+",
            timezones="UTC-03:00",
            dialing_code="+54",
            date_format="DD/MM/YYYY",
            internet_domain=".ar",
            payroll_frequency="Typically monthly",
            pay_currency="ARS",
            hero_intro="A payroll environment where local statutory precision and clear cost visibility should be treated as one operating challenge.",
            overview="Argentina benefits from a country page that combines employer facts, payroll framing, and a strong executive story about local payroll control and reporting discipline.",
            standard_working_week="Typically around 48 hours",
        ),
        build_profile(
            sort_order=10,
            slug="brazil",
            iso_code="BR",
            country_name="Brazil",
            official_name="Federative Republic of Brazil",
            capital="Brasilia",
            primary_languages="Portuguese",
            currency="Brazilian real (BRL)",
            population_display="203M+",
            timezones="UTC-05:00 to UTC-02:00",
            dialing_code="+55",
            date_format="DD/MM/YYYY",
            internet_domain=".br",
            payroll_frequency="Monthly",
            pay_currency="BRL",
            hero_intro="A high-volume payroll market where monthly control, statutory accuracy, and clean reporting discipline matter from the first cycle.",
            overview="ExactusPay positions Brazil as a control-heavy payroll market: one monthly rhythm, multiple statutory layers, and strong demand for evidence-backed reporting.",
            standard_working_week="Up to 44 hours",
        ),
        build_profile(
            sort_order=20,
            slug="chile",
            iso_code="CL",
            country_name="Chile",
            official_name="Republic of Chile",
            capital="Santiago",
            primary_languages="Spanish",
            currency="Chilean peso (CLP)",
            population_display="19M+",
            timezones="UTC-04:00 with seasonal variation",
            dialing_code="+56",
            date_format="DD-MM-YYYY",
            internet_domain=".cl",
            payroll_frequency="Monthly",
            pay_currency="CLP",
            hero_intro="A payroll market where local registration, clean worker setup, and strong statutory evidence create a smoother route to scale.",
            overview="The ExactusPay Chile page balances commercial readability with operational relevance and is structured for employers who need an at-a-glance country summary first.",
        ),
        build_profile(
            sort_order=30,
            slug="costa-rica",
            iso_code="CR",
            country_name="Costa Rica",
            official_name="Republic of Costa Rica",
            capital="San Jose",
            primary_languages="Spanish",
            currency="Costa Rican colon (CRC)",
            population_display="5M+",
            timezones="UTC-06:00",
            dialing_code="+506",
            date_format="DD/MM/YYYY",
            internet_domain=".cr",
            payroll_frequency="Monthly",
            pay_currency="CRC",
            hero_intro="A country page format built for employers who want a short, commercially clear summary before diving into payroll detail.",
            overview="Costa Rica demonstrates the fallback behaviour of the template: when a country has core metadata and a few operational notes, the page still reads cleanly while the payroll dataset grows.",
        ),
        build_profile(
            sort_order=40,
            slug="ethiopia",
            iso_code="ET",
            country_name="Ethiopia",
            official_name="Federal Democratic Republic of Ethiopia",
            capital="Addis Ababa",
            primary_languages="Amharic and regional languages",
            currency="Ethiopian birr (ETB)",
            population_display="126M+",
            timezones="UTC+03:00",
            dialing_code="+251",
            date_format="DD/MM/YYYY",
            internet_domain=".et",
            payroll_frequency="Typically monthly",
            pay_currency="ETB",
            hero_intro="A large labour market where payroll setup needs to stay practical, controlled, and easy to explain across teams.",
            overview="The Ethiopia country page gives ExactusPay a clean commercial entry point for market education while leaving room for deeper payroll detail over time.",
        ),
        build_profile(
            sort_order=50,
            slug="united-kingdom",
            iso_code="GB",
            country_name="United Kingdom",
            official_name="United Kingdom of Great Britain and Northern Ireland",
            capital="London",
            primary_languages="English",
            currency="Pound sterling (GBP)",
            population_display="68M+",
            timezones="UTC+00:00 / UTC+01:00",
            dialing_code="+44",
            date_format="DD/MM/YYYY",
            internet_domain=".uk",
            payroll_frequency="Monthly or weekly cycles are common",
            pay_currency="GBP",
            hero_intro="A mature payroll market where employers expect accuracy, strong controls, and clear employee-facing payroll operations.",
            overview="The United Kingdom profile fits buyers who want a recognisable market framed inside the same ExactusPay structure used across higher-growth regions.",
        ),
        build_profile(
            sort_order=60,
            slug="nigeria",
            iso_code="NG",
            country_name="Nigeria",
            official_name="Federal Republic of Nigeria",
            capital="Abuja",
            primary_languages="English",
            currency="Nigerian naira (NGN)",
            population_display="227M+",
            timezones="UTC+01:00",
            dialing_code="+234",
            date_format="DD/MM/YYYY",
            internet_domain=".ng",
            payroll_frequency="Typically monthly",
            pay_currency="NGN",
            hero_intro="A high-potential market where country payroll visibility helps employers move from fragmented local execution to a cleaner operating model.",
            overview="Nigeria is a strong example of why ExactusPay needs reusable country pages: local complexity, employer demand for clarity, and strong value in one reporting standard.",
        ),
        build_profile(
            sort_order=70,
            slug="netherlands",
            iso_code="NL",
            country_name="Netherlands",
            official_name="Kingdom of the Netherlands",
            capital="Amsterdam",
            primary_languages="Dutch",
            currency="Euro (EUR)",
            population_display="18M+",
            timezones="UTC+01:00 / UTC+02:00",
            dialing_code="+31",
            date_format="DD-MM-YYYY",
            internet_domain=".nl",
            payroll_frequency="Monthly or four-weekly cycles are common",
            pay_currency="EUR",
            hero_intro="A mature payroll market where employers still value a country page that translates payroll detail into a clear commercial summary.",
            overview="The Netherlands profile gives ExactusPay a reusable way to present established-market payroll context without breaking the same layout used elsewhere.",
        ),
        build_profile(
            sort_order=80,
            slug="pakistan",
            iso_code="PK",
            country_name="Pakistan",
            official_name="Islamic Republic of Pakistan",
            capital="Islamabad",
            primary_languages="Urdu and English",
            currency="Pakistani rupee (PKR)",
            population_display="241M+",
            timezones="UTC+05:00",
            dialing_code="+92",
            date_format="DD/MM/YYYY",
            internet_domain=".pk",
            payroll_frequency="Typically monthly",
            pay_currency="PKR",
            hero_intro="A large employer market where payroll setup, country context, and reliable internal communication all matter before execution scales.",
            overview="Pakistan benefits from the same reusable ExactusPay structure: facts first, payroll framing second, deeper market detail over time.",
        ),
        build_profile(
            sort_order=90,
            slug="egypt",
            iso_code="EG",
            country_name="Egypt",
            official_name="Arab Republic of Egypt",
            capital="Cairo",
            primary_languages="Arabic",
            currency="Egyptian pound (EGP)",
            population_display="114M+",
            timezones="UTC+02:00",
            dialing_code="+20",
            date_format="DD/MM/YYYY",
            internet_domain=".eg",
            payroll_frequency="Typically monthly",
            pay_currency="EGP",
            hero_intro="A major regional market where country-level payroll messaging helps employers balance compliance needs with operational simplicity.",
            overview="The Egypt country page uses ExactusPay's standard structure to support market education, payroll positioning, and future data expansion.",
        ),
        build_profile(
            sort_order=100,
            slug="india",
            iso_code="IN",
            country_name="India",
            official_name="Republic of India",
            capital="New Delhi",
            primary_languages="Hindi, English, and regional languages",
            currency="Indian rupee (INR)",
            population_display="1.4B+",
            timezones="UTC+05:30",
            dialing_code="+91",
            date_format="DD-MM-YYYY",
            internet_domain=".in",
            payroll_frequency="Typically monthly",
            pay_currency="INR",
            hero_intro="A large and strategically important payroll market where country context and reporting discipline should be visible from the first conversation.",
            overview="India is well suited to the ExactusPay country-page approach: high employer interest, strong need for payroll education, and room for richer data over time.",
        ),
        build_profile(
            sort_order=110,
            slug="indonesia",
            iso_code="ID",
            country_name="Indonesia",
            official_name="Republic of Indonesia",
            capital="Jakarta",
            primary_languages="Indonesian",
            currency="Indonesian rupiah (IDR)",
            population_display="281M+",
            timezones="UTC+07:00 to UTC+09:00",
            dialing_code="+62",
            date_format="DD/MM/YYYY",
            internet_domain=".id",
            payroll_frequency="Typically monthly",
            pay_currency="IDR",
            hero_intro="A multi-island employer market where one consistent payroll story is valuable for both implementation and executive visibility.",
            overview="Indonesia illustrates how ExactusPay can use one country-page system to present local payroll context in a commercially strong but scalable format.",
        ),
        build_profile(
            sort_order=120,
            slug="morocco",
            iso_code="MA",
            country_name="Morocco",
            official_name="Kingdom of Morocco",
            capital="Rabat",
            primary_languages="Arabic, Amazigh, French widely used in business",
            currency="Moroccan dirham (MAD)",
            population_display="37M+",
            timezones="UTC+01:00",
            dialing_code="+212",
            date_format="DD/MM/YYYY",
            internet_domain=".ma",
            payroll_frequency="Typically monthly",
            pay_currency="MAD",
            hero_intro="A payroll market where country-level guidance helps employers connect local execution with broader regional operating plans.",
            overview="The Morocco profile gives ExactusPay a reusable market page with room for richer payroll and statutory content as internal data sources mature.",
        ),
        build_profile(
            sort_order=130,
            slug="panama",
            iso_code="PA",
            country_name="Panama",
            official_name="Republic of Panama",
            capital="Panama City",
            primary_languages="Spanish",
            currency="Panamanian balboa (PAB) and US dollar (USD)",
            population_display="4M+",
            timezones="UTC-05:00",
            dialing_code="+507",
            date_format="DD/MM/YYYY",
            internet_domain=".pa",
            payroll_frequency="Typically monthly",
            pay_currency="PAB / USD",
            hero_intro="A payroll market where a concise, data-ready country page helps buyers understand the local operating frame quickly.",
            overview="Panama fits the ExactusPay reusable model well: short market introduction, payroll framing, and future expansion through platform-fed data points.",
        ),
        build_profile(
            sort_order=140,
            slug="peru",
            iso_code="PE",
            country_name="Peru",
            official_name="Republic of Peru",
            capital="Lima",
            primary_languages="Spanish, Quechua, and Aymara",
            currency="Peruvian sol (PEN)",
            population_display="34M+",
            timezones="UTC-05:00",
            dialing_code="+51",
            date_format="DD/MM/YYYY",
            internet_domain=".pe",
            payroll_frequency="Typically monthly",
            pay_currency="PEN",
            hero_intro="A payroll market where employers benefit from seeing country facts, payroll signals, and implementation context in one place.",
            overview="Peru demonstrates how ExactusPay can publish useful payroll market pages without waiting for every country feed to be fully populated.",
        ),
        build_profile(
            sort_order=150,
            slug="philippines",
            iso_code="PH",
            country_name="Philippines",
            official_name="Republic of the Philippines",
            capital="Manila",
            primary_languages="Filipino and English",
            currency="Philippine peso (PHP)",
            population_display="117M+",
            timezones="UTC+08:00",
            dialing_code="+63",
            date_format="MM/DD/YYYY",
            internet_domain=".ph",
            payroll_frequency="Semi-monthly cycles are common",
            pay_currency="PHP",
            hero_intro="A market where payroll cadence and local employee expectations make country-specific communication especially useful.",
            overview="The Philippines page uses the ExactusPay structure to combine market context, payroll rhythm, and a scalable path toward richer payroll intelligence.",
        ),
        build_profile(
            sort_order=160,
            slug="saudi-arabia",
            iso_code="SA",
            country_name="Saudi Arabia",
            official_name="Kingdom of Saudi Arabia",
            capital="Riyadh",
            primary_languages="Arabic",
            currency="Saudi riyal (SAR)",
            population_display="33M+",
            timezones="UTC+03:00",
            dialing_code="+966",
            date_format="DD/MM/YYYY",
            internet_domain=".sa",
            payroll_frequency="Typically monthly",
            pay_currency="SAR",
            hero_intro="A strategically important employer market where payroll and compliance positioning should be communicated with confidence and clarity.",
            overview="Saudi Arabia benefits from a reusable country page that can support both commercial conversations and richer payroll implementation detail later.",
        ),
        build_profile(
            sort_order=170,
            slug="south-africa",
            iso_code="ZA",
            country_name="South Africa",
            official_name="Republic of South Africa",
            capital="Pretoria, Cape Town, and Bloemfontein",
            primary_languages="English and multiple official languages",
            currency="South African rand (ZAR)",
            population_display="63M+",
            timezones="UTC+02:00",
            dialing_code="+27",
            date_format="YYYY/MM/DD",
            internet_domain=".za",
            payroll_frequency="Typically monthly",
            pay_currency="ZAR",
            hero_intro="A payroll market where employers need strong control over local payroll operations and a clean regional reporting layer.",
            overview="South Africa is a strong ExactusPay country-page candidate because it combines commercial importance, payroll process sensitivity, and reporting expectations.",
        ),
        build_profile(
            sort_order=180,
            slug="turkey",
            iso_code="TR",
            country_name="Turkey",
            official_name="Republic of Türkiye",
            capital="Ankara",
            primary_languages="Turkish",
            currency="Turkish lira (TRY)",
            population_display="86M+",
            timezones="UTC+03:00",
            dialing_code="+90",
            date_format="DD.MM.YYYY",
            internet_domain=".tr",
            payroll_frequency="Typically monthly",
            pay_currency="TRY",
            hero_intro="A country profile that helps explain local payroll context without losing the consistency of the wider ExactusPay market structure.",
            overview="Turkey works well in this reusable model because the page can support both commercial discovery and future payroll intelligence enrichment.",
        ),
        build_profile(
            sort_order=190,
            slug="united-arab-emirates",
            iso_code="AE",
            country_name="United Arab Emirates",
            official_name="United Arab Emirates",
            capital="Abu Dhabi",
            primary_languages="Arabic and English widely used in business",
            currency="UAE dirham (AED)",
            population_display="10M+",
            timezones="UTC+04:00",
            dialing_code="+971",
            date_format="DD/MM/YYYY",
            internet_domain=".ae",
            payroll_frequency="Typically monthly",
            pay_currency="AED",
            hero_intro="A market where employers expect payroll reliability, strong employee experience, and clear visibility into local operating realities.",
            overview="The UAE country page extends the ExactusPay template into a commercially important market while keeping the same reusable layout and data contract.",
        ),
    ]

    for payload in profiles:
        CountryProfile.objects.update_or_create(
            slug=payload["slug"],
            defaults=payload,
        )


def remove_additional_country_profiles(apps, schema_editor):
    CountryProfile = apps.get_model("home", "CountryProfile")
    CountryProfile.objects.filter(
        slug__in=[
            "angola",
            "argentina",
            "brazil",
            "chile",
            "costa-rica",
            "ethiopia",
            "united-kingdom",
            "nigeria",
            "netherlands",
            "pakistan",
            "egypt",
            "india",
            "indonesia",
            "morocco",
            "panama",
            "peru",
            "philippines",
            "saudi-arabia",
            "south-africa",
            "turkey",
            "united-arab-emirates",
        ]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_seed_country_profiles"),
    ]

    operations = [
        migrations.RunPython(seed_additional_country_profiles, remove_additional_country_profiles),
    ]
