# Generated by Django 5.2.8 on 2025-12-03 14:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0002_company_county'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('SYSTEM', 'System Notification'), ('PAYROLL', 'Payroll Update'), ('APPROVAL', 'Approval Required'), ('DEADLINE', 'Deadline Reminder'), ('EMPLOYEE', 'Employee Action'), ('COMPLIANCE', 'Compliance Alert'), ('SECURITY', 'Security Alert'), ('BILLING', 'Billing Update'), ('SUPPORT', 'Support Response')], default='SYSTEM', max_length=20)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Informational')], default='INFO', max_length=20)),
                ('action_url', models.URLField(blank=True, null=True)),
                ('action_label', models.CharField(blank=True, max_length=100)),
                ('reference_model', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('sms_sent', models.BooleanField(default=False)),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'accounts_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Company Administrator'), ('PAYROLL_MANAGER', 'Payroll Manager'), ('HR_MANAGER', 'HR Manager'), ('FINANCE', 'Finance Team'), ('MANAGER', 'Department Manager'), ('VIEWER', 'Viewer'), ('EMPLOYEE', 'Employee (Self-Service)')], default='VIEWER', max_length=50)),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Additional permissions specific to this user-company relationship')),
                ('is_active', models.BooleanField(default=True)),
                ('access_granted_at', models.DateTimeField(auto_now_add=True)),
                ('access_revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_access_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Company Access',
                'verbose_name_plural': 'User Company Access',
                'db_table': 'accounts_user_company',
            },
        ),
        migrations.RemoveIndex(
            model_name='rolehierarchy',
            name='accounts_ro_parent_d20745_idx',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='company.company'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_password_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_frequency',
            field=models.CharField(choices=[('IMMEDIATE', 'Immediately'), ('DAILY', 'Daily Digest'), ('WEEKLY', 'Weekly Digest')], default='IMMEDIATE', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('EXPORT', 'Export'), ('PERMISSION_CHANGE', 'Permission Change'), ('SECURITY_EVENT', 'Security Event'), ('OTHER', 'Other'), ('NOTIFICATION_CREATED', 'Notification Created'), ('NOTIFICATION_READ', 'Notification Read'), ('COMPANY_ACCESS_GRANTED', 'Company Access Granted'), ('COMPANY_ACCESS_REVOKED', 'Company Access Revoked')], max_length=50),
        ),
        migrations.AlterField(
            model_name='permissionmatrix',
            name='domain',
            field=models.CharField(choices=[('ALL', 'All'), ('RULE', 'Regulation'), ('COMPANY', 'Company'), ('PAYROLL', 'Payroll'), ('PERIOD', 'Payroll Period'), ('EMPLOYEE', 'Employee'), ('REPORT', 'Reports'), ('USER', 'User Management'), ('ROLE', 'Role Management'), ('COMPANY_USER', 'Company User Management'), ('NOTIFICATION', 'Notification Management')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='accounts_au_user_id_7b1069_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='accounts_au_action_c683b9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['company', 'created_at'], name='accounts_au_company_db2e10_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='accounts_au_created_606b86_idx'),
        ),
        migrations.AddIndex(
            model_name='customrole',
            index=models.Index(fields=['scope', 'is_active'], name='accounts_cu_scope_07f60c_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionmatrix',
            index=models.Index(fields=['role', 'domain', 'action'], name='accounts_pe_role_c77686_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionmatrix',
            index=models.Index(fields=['role'], name='accounts_pe_role_5b0f7a_idx'),
        ),
        migrations.AddIndex(
            model_name='rolehierarchy',
            index=models.Index(fields=['parent'], name='accounts_ro_parent_32c348_idx'),
        ),
        migrations.AddIndex(
            model_name='rolehierarchy',
            index=models.Index(fields=['child'], name='accounts_ro_child_951452_idx'),
        ),
        migrations.AddField(
            model_name='notification',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='company.company'),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='access_granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_users', to='company.company'),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read', 'archived'], name='accounts_no_user_id_41f18a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'notification_type'], name='accounts_no_user_id_65e69b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='accounts_no_user_id_501ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['expires_at'], name='accounts_no_expires_c7af83_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['company'], name='accounts_no_company_5cb247_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority', 'created_at'], name='accounts_no_priorit_81b80c_idx'),
        ),
        migrations.AddIndex(
            model_name='usercompany',
            index=models.Index(fields=['user', 'company'], name='accounts_us_user_id_3e49cf_idx'),
        ),
        migrations.AddIndex(
            model_name='usercompany',
            index=models.Index(fields=['company', 'role'], name='accounts_us_company_13b364_idx'),
        ),
        migrations.AddIndex(
            model_name='usercompany',
            index=models.Index(fields=['user', 'is_active'], name='accounts_us_user_id_a5364b_idx'),
        ),
        migrations.AddIndex(
            model_name='usercompany',
            index=models.Index(fields=['role'], name='accounts_us_role_a7510e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercompany',
            unique_together={('user', 'company')},
        ),
    ]
