# Generated by Django 5.2.8 on 2025-11-26 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdcode_code', models.CharField(blank=True, max_length=50, null=True)),
                ('pdcode_description', models.CharField(max_length=150)),
                ('pdcode_name', models.CharField(max_length=150)),
                ('pdcode_status', models.CharField(blank=True, choices=[('Visible', 'Visible'), ('Hidden', 'Hidden')], max_length=15, null=True)),
                ('pdcode_account', models.IntegerField(blank=True, null=True)),
                ('pdcode_map_code', models.IntegerField(blank=True, null=True)),
                ('pdcode_gl_account', models.IntegerField(blank=True, null=True)),
                ('pdcode_frequency', models.CharField(blank=True, choices=[('Recurring', 'Recurring'), ('Non-recurring', 'Non-recurring')], max_length=15, null=True)),
                ('pdcode_type', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Irregular', 'Irregular')], max_length=50, null=True)),
                ('pdcode_class', models.CharField(blank=True, choices=[('Standard', 'Standard'), ('Statutory', 'Statutory')], max_length=50, null=True)),
                ('pdcode_category', models.CharField(blank=True, choices=[('Payment', 'Payment'), ('Deduction', 'Deduction'), ('Notional', 'Notional'), ('Base', 'Base'), ('Gross up', 'Gross up'), ('ER Contribution', 'ER Contribution'), ('ER Cost', 'ER Cost')], max_length=50, null=True)),
                ('pdcode_taxable', models.BooleanField(default=False)),
                ('pdcode_tax_flat', models.BooleanField(default=False)),
                ('pdcode_tax_irregular', models.BooleanField(default=False)),
                ('pdcode_social_securitable', models.BooleanField(default=False)),
                ('pdcode_pensionable', models.BooleanField(default=False)),
                ('pdcode_payable', models.BooleanField(default=False)),
                ('pdcode_calculate', models.BooleanField(default=False)),
                ('pdcode_categorytype', models.CharField(blank=True, choices=[('Bracketable', 'Bracketable'), ('Prorational', 'Prorational'), ('Pension', 'Pension'), ('Formulae', 'Formulae'), ('Base', 'Base')], max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdcodes', to='company.company')),
            ],
            options={
                'ordering': ['pdcode_code'],
                'unique_together': {('company', 'pdcode_code')},
            },
        ),
    ]
