# Generated by Django 5.2.8 on 2026-01-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdcodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdcode',
            name='pdcode_account',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdcode',
            name='pdcode_gl_account',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdcode',
            name='pdcode_map_code',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
