# Generated by Django 5.2.8 on 2026-02-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdcodes", "0002_alter_pdcode_pdcode_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdcode",
            name="pdcode_categorytype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Bracketable", "Bracketable"),
                    ("Prorational", "Prorational"),
                    ("Formulae", "Formulae"),
                    ("Base", "Base"),
                    ("Accrual", "Accrual"),
                    ("Flat", "Flat"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
