# Generated by Django 5.2.8 on 2025-11-19 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_code', models.CharField(max_length=20, verbose_name='Company Code')),
                ('company_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Company Number')),
                ('trade_name', models.CharField(max_length=150, verbose_name='Trade Name')),
                ('legal_name', models.CharField(max_length=150, verbose_name='Legal Name')),
                ('building_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Building Name')),
                ('road_name_1', models.CharField(blank=True, max_length=150, null=True, verbose_name='Road Name 1')),
                ('road_name_2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Road Name 2')),
                ('town', models.CharField(blank=True, max_length=100, null=True, verbose_name='Town')),
                ('post_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Post Code')),
                ('tax_id_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 1')),
                ('tax_id_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 2')),
                ('tax_id_3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 3')),
                ('tax_id_4', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 4')),
                ('tax_id_5', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 5')),
                ('tax_id_6', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 6')),
                ('tax_id_7', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 7')),
                ('tax_id_8', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 8')),
                ('tax_id_9', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 9')),
                ('tax_id_10', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 10')),
                ('rti_user_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='RTI User ID')),
                ('rti_password', models.CharField(blank=True, max_length=100, null=True, verbose_name='RTI Password')),
                ('account_status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10, verbose_name='Account Status')),
                ('account_archive', models.CharField(choices=[('N', 'NO'), ('Y', 'YES')], default='N', max_length=10, verbose_name='Account Archive')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='country.country')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['trade_name'],
            },
        ),
    ]
