# Generated by Django 5.2.8 on 2025-11-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_code',
            field=models.CharField(max_length=20, verbose_name='Company Code'),
        ),
    ]
