# Generated by Django 5.2.8 on 2025-11-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_company_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Town'),
        ),
    ]
