# Generated by Django 5.2.8 on 2025-11-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_town'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='account_archive',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10, verbose_name='Account Archive'),
        ),
    ]
