# Generated by Django 5.2.8 on 2025-11-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_account_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='account_archive',
            field=models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], default='NO', max_length=10, verbose_name='Account Archive'),
        ),
    ]
