# Generated by Django 5.2.8 on 2025-12-05 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculationbase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationbase',
            name='ss_category',
        ),
        migrations.RemoveField(
            model_name='calculationbase',
            name='table_type',
        ),
        migrations.RemoveField(
            model_name='calculationbase',
            name='tax_jurisdiction',
        ),
    ]
