# Generated by Django 5.2.8 on 2026-01-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculationbase', '0008_alter_calculationbase_bracket_00_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationbase',
            name='rounding_base_decimals',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AlterField(
            model_name='calculationbase',
            name='rounding_taxed_decimals',
            field=models.IntegerField(blank=True, default=2),
        ),
    ]
