# Generated by Django 5.2.8 on 2025-11-20 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Employee ID')),
                ('employee_number', models.IntegerField(verbose_name='Employee Number')),
                ('employee_code', models.IntegerField(verbose_name='Employee Code')),
                ('employee_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('employee_surname', models.CharField(max_length=100, verbose_name='Last Name')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=20, null=True, verbose_name='Marital Status')),
                ('employee_address_type', models.CharField(blank=True, choices=[('Residential', 'Residential'), ('Correspondence', 'Correspondence')], max_length=20, null=True, verbose_name='Address Type')),
                ('employee_address_01', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 1')),
                ('employee_address_02', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 2')),
                ('employee_address_03', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 3')),
                ('employee_address_04', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 4')),
                ('employee_address_05', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 5')),
                ('employee_address_06', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 6')),
                ('employee_address_07', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 7')),
                ('bank_01', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_02', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_03', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_04', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_05', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_06', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_07', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_08', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_09', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_10', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Department')),
                ('cost_centre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cost Centre')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Title')),
                ('position_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Position Number')),
                ('fte', models.CharField(blank=True, max_length=100, null=True, verbose_name='FTE')),
                ('tax_info_01', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_info_02', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_info_03', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_info_04', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_info_05', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_info_06', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_info_07', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='company.company')),
            ],
            options={
                'verbose_name_plural': 'Employees',
                'ordering': ['employee_surname', 'employee_name'],
            },
        ),
    ]
