# Generated by Django 5.2.8 on 2025-12-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_cost_centre_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cost_centre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cost Centre'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_address_01',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_address_02',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_address_03',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 3'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_address_04',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 4'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_address_05',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 5'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_address_06',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 6'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_address_07',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 7'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fte',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='FTE'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Position Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tax_info_07',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
