# Generated by Django 5.2.8 on 2025-12-03 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='fiscal_year_end',
        ),
        migrations.RemoveField(
            model_name='country',
            name='fiscal_year_start',
        ),
    ]
