# Generated by Django 5.2.8 on 2025-12-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='county',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='County'),
        ),
    ]
