# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='County'),
        ),
    ]
