# Generated by Django 5.2.8 on 2025-12-03 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_county'),
        ('country', '0002_remove_country_fiscal_year_end_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['trade_name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='company_code',
            field=models.CharField(help_text='Unique identifier for the company', max_length=20, verbose_name='Company Code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_number',
            field=models.CharField(blank=True, help_text='Official registration number', max_length=50, null=True, verbose_name='Company Number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='country.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='County/State/Province'),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_name',
            field=models.CharField(help_text='Registered legal name', max_length=150, verbose_name='Legal Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='rti_password',
            field=models.CharField(blank=True, help_text='Password for payroll reporting', max_length=100, null=True, verbose_name='RTI Password'),
        ),
        migrations.AlterField(
            model_name='company',
            name='rti_user_id',
            field=models.CharField(blank=True, help_text='Username for payroll reporting', max_length=100, null=True, verbose_name='RTI User ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Town/City'),
        ),
        migrations.AlterField(
            model_name='company',
            name='trade_name',
            field=models.CharField(help_text='Business/trading name', max_length=150, verbose_name='Trade Name'),
        ),
    ]
