# Generated by Django 5.2.8 on 2025-12-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_options_alter_company_company_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tax_id_11',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 1'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_id_12',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 2'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_id_13',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 3'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_id_14',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 4'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_id_15',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 5'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_id_16',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 6'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_id_17',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 7'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_id_18',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 8'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_id_19',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 9'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_id_20',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 10'),
        ),
    ]
