# Generated by Django 5.2.8 on 2026-01-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_agent_full_name_company_agent_post_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('companies', models.ManyToManyField(blank=True, help_text='Select all companies belonging to this client group.', related_name='client_groups', to='company.company')),
            ],
            options={
                'verbose_name': 'Client Group',
                'verbose_name_plural': 'Client Groups',
            },
        ),
    ]
