# Generated by Django 5.2.8 on 2025-12-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_tax_id_11_company_tax_id_12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to='company_logos/'),
        ),
    ]
