# Generated by Django 5.2.8 on 2025-12-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tax_id_11',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 11'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id_12',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 12'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id_13',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 13'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id_14',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 14'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id_15',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 15'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id_16',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 16'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id_17',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 17'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id_18',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 18'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id_19',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 19'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id_20',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID 20'),
        ),
    ]
