# Generated by Django 5.2.8 on 2025-12-18 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_company_bank_01_company_bank_02_company_bank_03_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='tax_id_1',
            new_name='tax_id_01',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='tax_id_2',
            new_name='tax_id_02',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='tax_id_3',
            new_name='tax_id_03',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='tax_id_4',
            new_name='tax_id_04',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='tax_id_5',
            new_name='tax_id_05',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='tax_id_6',
            new_name='tax_id_06',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='tax_id_7',
            new_name='tax_id_07',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='tax_id_8',
            new_name='tax_id_08',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='tax_id_9',
            new_name='tax_id_09',
        ),
    ]
