# Generated by Django 5.2.8 on 2025-11-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
