# Generated by Django 5.2.8 on 2026-01-28 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0004_clientgroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Report Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('source_model', models.CharField(choices=[('PayrollResult', 'Payroll Results (Payslips)'), ('Employee', 'Employee Data'), ('PayrollPeriod', 'Payroll Periods Summary')], default='PayrollResult', max_length=50)),
                ('selected_fields', models.JSONField(default=list, help_text='List of fields to include in the report')),
                ('allow_date_range', models.BooleanField(default=True, verbose_name='Filter by Date Range')),
                ('allow_payroll_selection', models.BooleanField(default=True, verbose_name='Filter by Specific Payroll')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
