# Generated by Django 5.2.8 on 2026-01-29 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_clientgroup'),
        ('reports', '0002_reportdefinition_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportdefinition',
            name='country',
        ),
        migrations.AlterField(
            model_name='reportdefinition',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
    ]
