# Generated by Django 5.2.8 on 2026-01-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_reportdefinition_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdefinition',
            name='is_ytd',
            field=models.BooleanField(default=False, help_text='If checked, values will be summed from the start of the tax year up to the selected period.', verbose_name='Year To Date (YTD)'),
        ),
    ]
