# Generated by Django 5.2.8 on 2026-01-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_reportdefinition_is_ytd'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdefinition',
            name='is_comparison',
            field=models.BooleanField(default=False, help_text='If checked, compares the selected period against the previous period.', verbose_name='Comparison Report'),
        ),
    ]
